Repository sumup-oss/circuit-ui, pull requests merged in 2018-10, with the labels that each got.

#295 Sliding in a new neutral
  docs/content/styles/colors.mdx
  src/themes/circuit.js
Labels: enhancement, ready for review

#299 [MW-1082] Add Union Pay logo to card schemes
  src/components/CardSchemes/__snapshots__/CardSchemes.spec.js.snap
  src/components/CreditCardDetails/components/scheme-icons/card-scheme-icons.js
  src/components/CreditCardDetails/components/scheme-icons/icons/union-pay.svg
Labels: enhancement, ready for review

#304 Fix Snapshot of Select component
  src/components/Select/__snapshots__/Select.spec.js.snap
Labels: bug, ready for review

#307 Export Spinner component
  src/index.js
Labels: ready for review
