Repository sumup-oss/circuit-ui, pull requests merged in 2018-06, with the labels that each got.

#186 Export size enums on Button component
  src/components/Button/Button.js
  src/components/Button/__snapshots__/Button.spec.js.snap
Labels: enhancement, ready for review

#195 Show content that overflows a Card
  src/components/Card/Card.js
  src/components/Card/__snapshots__/Card.spec.js.snap
  src/components/Modal/components/ModalWrapper/__snapshots__/ModalWrapper.spec.js.snap
  src/components/NotificationList/__snapshots__/NotificationList.spec.js.snap
Labels: bug, ready for review

#181 Make Circuit UI safe to use with SSR
  src/util/ios.js
Labels: enhancement, ready for review

#198 Use black text for success and warning
  src/components/InlineNotification/InlineNotification.js
  src/components/InlineNotification/__snapshots__/InlineNotification.spec.js.snap
Labels: enhancement, ready for review

#197 Fix button margin on larger screens
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/ButtonGroup.story.js
  src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.js.snap
Labels: bug, ready for review

#184 Introduce @sumup/foundry into the project
  bin/create-component
  package.json
  plopfile.js
  yarn.lock
Labels: ready for review, tech

#183 Pass value prop down to select element
  src/components/Select/Select.js
  src/components/Select/__snapshots__/Select.spec.js.snap
Labels: bug, ready for review

#182 Update Git hooks
  package.json
  yarn.lock
Labels: ready for review, tech

#187 Add plain Button variant
  package.json
  src/components/Button/Button.js
  src/components/Button/Button.spec.js
  src/components/Button/Button.story.js
  src/components/Button/components/PlainButton/PlainButton.js
  src/components/Button/components/PlainButton/PlainButton.spec.js
  src/components/Button/components/PlainButton/__snapshots__/PlainButton.spec.js.snap
  src/components/Button/components/PlainButton/index.js
  src/components/Button/components/RegularButton/RegularButton.js
  src/components/Button/components/RegularButton/RegularButton.spec.js
  src/components/Button/components/RegularButton/__snapshots__/RegularButton.spec.js.snap
  src/components/Button/components/RegularButton/index.js
  src/components/Button/constants.js
  src/components/LoadingButton/Container.spec.js
  src/components/LoadingButton/components/LoadingButton/__snapshots__/index.spec.js.snap
  src/components/LoadingButton/components/LoadingButton/index.spec.js
  src/components/Text/Text.js
  src/components/Text/index.js
  src/index.js
Labels: ready for review

#203 Add shadow variant to Table component
  src/components/Table/Table.js
  src/components/Table/Table.spec.js
  src/components/Table/Table.story.js
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/TableRow/index.js
Labels: ready for review

#205 Run ESLint only on staged changes
  package.json
Labels: bug, ready for review, tech

#204 Add accessibleOnly prop to Label
  src/components/Label/Label.js
  src/components/Label/Label.spec.js
  src/components/Label/Label.story.js
  src/components/Label/__snapshots__/Label.spec.js.snap
Labels: enhancement, ready for review

#215 Add giga size to List component
  src/components/List/List.js
  src/components/List/List.spec.js
  src/components/List/List.story.js
  src/components/List/__snapshots__/List.spec.js.snap
Labels: enhancement, ready for review

#212 Replace enzyme context patch
  package.json
  yarn.lock
Labels: ready for review, tech

#213 Improve styling of Checkbox component
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
Labels: enhancement, ready for review

#210 Add Hamburger component
  src/components/Hamburger/Hamburger.js
  src/components/Hamburger/Hamburger.spec.js
  src/components/Hamburger/Hamburger.story.js
  src/components/Hamburger/__snapshots__/Hamburger.spec.js.snap
  src/components/Hamburger/index.js
  src/index.js
Labels: enhancement, ready for review
