Repository sumup-oss/circuit-ui, pull requests merged in 2018-12, with the labels that each got.

#324 Export Masked and Restricted Input
  src/index.js
Labels: bug, ready for review

#326 [Bug] "Text is not defined" in ListView
  src/components/ListView/components/Item/components/Wrapper/Wrapper.js
Labels: bug, ready for review

#322 Update modal.mdx
  docs/content/components/modal.mdx
Labels: enhancement, ready for review

#323 Update spacing.mdx
  docs/content/styles/spacing.mdx
Labels: enhancement, in progress

#317 Create Pagination Component
  src/components/Pagination/PageButton/PageButton.js
  src/components/Pagination/PageButton/PageButton.spec.js
  src/components/Pagination/PageButton/__snapshots__/PageButton.spec.js.snap
  src/components/Pagination/PageButton/index.js
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.spec.js
  src/components/Pagination/Pagination.story.js
  src/components/Pagination/PaginationButton/PaginationButton.js
  src/components/Pagination/PaginationButton/PaginationButton.spec.js
  src/components/Pagination/PaginationButton/__snapshots__/PaginationButton.spec.js.snap
  src/components/Pagination/PaginationButton/index.js
  src/components/Pagination/PaginationContainer/PaginationContainer.js
  src/components/Pagination/PaginationContainer/PaginationContainer.spec.js
  src/components/Pagination/PaginationContainer/__snapshots__/PaginationContainer.spec.js.snap
  src/components/Pagination/PaginationContainer/index.js
  src/components/Pagination/PaginationService.js
  src/components/Pagination/PaginationService.spec.js
  src/components/Pagination/__snapshots__/Pagination.spec.js.snap
  src/components/Pagination/index.js
Labels: ready for review

#319 [Docs] Add code of conduct
  CODE_OF_CONDUCT.md
Labels: ready for review

#332 [Bug] Fix value for Select placeholder
  src/components/Select/Select.js
  src/components/Select/__snapshots__/Select.spec.js.snap
Labels: bug, ready for review

#330 [Bugfix] Update Table component to handle rows update while keeping sort
  src/components/Table/Table.js
  src/components/Table/Table.spec.js
  src/components/Table/Table.story.js
  src/components/Table/utils.js
  src/components/Table/utils.spec.js
Labels: bug, ready for review

#333 v0.0.15-canary
  package.json
Labels: ready for review

#334 [Bugfix] Handle text overflow in Select
  package.json
  src/components/Select/Select.js
  src/components/Select/__snapshots__/Select.spec.js.snap
Labels: bug, ready for review
