Repository sumup-oss/circuit-ui, pull requests merged in 2018-05, with the labels that each got.

#151 Add and use MaskedInput component
  package.json
  src/components/CreditCardDetails/CreditCardDetails.story.js
  src/components/CreditCardDetails/components/CardNumberInput/CardNumberInput.js
  src/components/CreditCardDetails/components/CardNumberInput/CardNumberInput.spec.js
  src/components/CreditCardDetails/components/CardNumberInput/CardNumberInput.story.js
  src/components/CreditCardDetails/components/CardNumberInput/CardNumberInputService.js
  src/components/CreditCardDetails/components/CardNumberInput/CardNumberInputService.spec.js
  src/components/CreditCardDetails/components/CardNumberInput/__snapshots__/CardNumberInput.spec.js.snap
  src/components/CreditCardDetails/components/CardNumberInput/index.js
  src/components/CreditCardDetails/components/ExpiryDateInput/ExpiryDateInput.js
  src/components/CreditCardDetails/components/ExpiryDateInput/ExpiryDateInput.spec.js
  src/components/CreditCardDetails/components/ExpiryDateInput/ExpiryDateInputService.js
  src/components/CreditCardDetails/components/ExpiryDateInput/ExpiryDateInputService.spec.js
  src/components/CreditCardDetails/components/SecurityCodeInput/SecurityCodeInput.js
  src/components/CreditCardDetails/components/SecurityCodeInput/SecurityCodeInputService.js
  src/components/CreditCardDetails/components/SecurityCodeInput/SecurityCodeInputService.spec.js
  src/components/CurrencyInput/CurrencyInput.js
  src/components/CurrencyInput/CurrencyInputService.js
  src/components/CurrencyInput/CurrencyInputService.spec.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/SimpleCurrencyInput.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/SimpleCurrencyInput.spec.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/SimpleCurrencyInput.story.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/__snapshots__/SimpleCurrencyInput.spec.js.snap
  src/components/HtmlElement/HtmlElement.js
  src/components/Input/Input.js
  src/components/MaskedInput/MaskedInput.js
  src/components/MaskedInput/MaskedInput.spec.js
  src/components/MaskedInput/MaskedInput.story.js
  src/components/MaskedInput/index.js
  src/index.js
  src/util/fp.js
  src/util/numbers.js
  yarn.lock
Labels: bug, done, enhancement

#147 Fix checkboxes compatibility with Final Form
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/Checkbox.spec.js
  src/components/Checkbox/Checkbox.story.js
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
  src/components/CheckboxGroup/CheckboxGroup.js
  src/components/CheckboxGroup/CheckboxGroup.spec.js
  src/components/CheckboxGroup/CheckboxGroup.story.js
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.spec.js.snap
  src/components/CheckboxGroup/index.js
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/__snapshots__/RadioButton.spec.js.snap
  src/components/RadioButtonGroup/__snapshots__/RadioButtonGroup.spec.js.snap
  src/index.js
Labels: done

#158 Ensure masks are overwritable in CC components
  src/components/CreditCardDetails/components/CardNumberInput/CardNumberInput.js
  src/components/CreditCardDetails/components/ExpiryDateInput/ExpiryDateInput.js
Labels: done, enhancement, ready for review

#164 Correctly normalize amounts ending in "00"
  src/components/CurrencyInput/CurrencyInputService.js
  src/components/CurrencyInput/CurrencyInputService.spec.js
Labels: bug, done, ready for review

#163 Change CalendarButton to use <Tag />
  .storybook/addons.js
  package.json
  src/components/CalendarButton/__snapshots__/CalendarButton.spec.js.snap
  src/components/CalendarButton/index.js
  src/components/CalendarButtonTwoStep/__snapshots__/CalendarButtonTwoStep.spec.js.snap
  src/components/CalendarButtonTwoStep/index.js
  src/components/CalendarTag/CalendarTag.js
  src/components/CalendarTag/CalendarTag.spec.js
  src/components/CalendarTag/CalendarTag.story.js
  src/components/CalendarTag/__snapshots__/CalendarTag.spec.js.snap
  src/components/CalendarTag/index.js
  src/components/CalendarTagTwoStep/CalendarTagTwoStep.js
  src/components/CalendarTagTwoStep/CalendarTagTwoStep.spec.js
  src/components/CalendarTagTwoStep/CalendarTagTwoStep.story.js
  src/components/CalendarTagTwoStep/__snapshots__/CalendarTagTwoStep.spec.js.snap
  src/components/CalendarTagTwoStep/index.js
  src/components/Tag/Tag.js
  src/components/Tag/Tag.story.js
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/index.js
  src/styles/style-helpers.js
Labels: done, ready for review

#160 Support Page integration with Circuit-UI
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/ButtonGroup.spec.js
  src/components/ButtonGroup/ButtonGroup.story.js
  src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.js.snap
  src/components/Card/Card.js
  src/components/Card/Card.story.js
  src/components/Card/__snapshots__/Card.spec.js.snap
  src/components/Card/components/Footer/Footer.js
  src/components/Card/components/Footer/Footer.spec.js
  src/components/Card/components/Footer/__snapshots__/Footer.spec.js.snap
  src/components/Input/Input.js
  src/components/Input/__snapshots__/Input.spec.js.snap
  src/components/NotificationList/__snapshots__/NotificationList.spec.js.snap
  src/components/RestrictedInput/RestrictedInput.js
  src/components/Select/Select.js
  src/components/Spacing/Spacing.js
  src/components/Spacing/Spacing.spec.js
  src/components/Spacing/Spacing.story.js
  src/components/Spacing/__snapshots__/Spacing.spec.js.snap
  src/components/Spacing/index.js
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
  src/components/Tooltip/Tooltip.js
  src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap
  src/index.js
  src/styles/constants.js
  src/themes/default.js
Labels: ready for review

#170 Don't overwrite props in Checkbox & RadioButton components
  src/components/Checkbox/Checkbox.js
  src/components/RadioButton/RadioButton.js
Labels: enhancement, ready for review

#172 [TOOL-56] Create Table component
  src/components/Table/Table.js
  src/components/Table/Table.spec.js
  src/components/Table/Table.story.js
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/SortArrow/__snapshots__/index.spec.js.snap
  src/components/Table/components/SortArrow/arrow.svg
  src/components/Table/components/SortArrow/index.js
  src/components/Table/components/SortArrow/index.spec.js
  src/components/Table/components/TableBody/__snapshots__/index.spec.js.snap
  src/components/Table/components/TableBody/index.js
  src/components/Table/components/TableBody/index.spec.js
  src/components/Table/components/TableCell/__snapshots__/index.spec.js.snap
  src/components/Table/components/TableCell/index.js
  src/components/Table/components/TableCell/index.spec.js
  src/components/Table/components/TableCell/index.story.js
  src/components/Table/components/TableHead/__snapshots__/index.spec.js.snap
  src/components/Table/components/TableHead/index.js
  src/components/Table/components/TableHead/index.spec.js
  src/components/Table/components/TableHeader/__snapshots__/index.spec.js.snap
  src/components/Table/components/TableHeader/index.js
  src/components/Table/components/TableHeader/index.spec.js
  src/components/Table/components/TableHeader/index.story.js
  src/components/Table/components/TableRow/index.js
  src/components/Table/constants.js
  src/components/Table/index.js
  src/components/Table/utils.js
  src/components/Table/utils.spec.js
  src/themes/default.js
Labels: ready for review

#173 Refactor usage of Modals
  src/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/CreditCardDetails/components/ExpiryDateInput/ExpiryDateInput.js
  src/components/CreditCardDetails/components/ExpiryDateInput/ExpiryDateInputService.spec.js
  src/components/Modal/Modal.embed.story.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.spec.js
  src/components/Modal/Modal.story.js
  src/components/Modal/ModalProvider.js
  src/components/Modal/components/ModalHeader/ModalHeader.js
  src/components/Modal/components/ModalHeader/ModalHeader.spec.js
  src/components/Modal/components/ModalHeader/__snapshots__/ModalHeader.spec.js.snap
  src/components/Modal/components/ModalHeader/index.js
  src/components/Modal/components/ModalWrapper/ModalWrapper.js
  src/components/Modal/components/ModalWrapper/ModalWrapper.spec.js
  src/components/Modal/components/ModalWrapper/__snapshots__/ModalWrapper.spec.js.snap
  src/components/Modal/components/ModalWrapper/index.js
  src/components/Modal/components/index.js
  src/components/Modal/index.js
  src/components/SvgButton/SvgButton.js
  src/components/SvgButton/__snapshots__/SvgButton.spec.js.snap
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/SortArrow/__snapshots__/index.spec.js.snap
  src/components/Table/components/TableHead/__snapshots__/index.spec.js.snap
  src/components/Table/components/TableHeader/__snapshots__/index.spec.js.snap
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/index.js
Labels: do not merge

#179 Export Markdown component
  package.json
  src/index.js
  yarn.lock
Labels: bug, ready for review

#139 Allow button to handle loading state
  jest.setup.js
  src/components/Button/Button.js
  src/components/Button/Button.spec.js
  src/components/Button/__snapshots__/Button.spec.js.snap
  src/components/Button/constants.js
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.js.snap
  src/components/LoadingButton/Container.js
  src/components/LoadingButton/Container.spec.js
  src/components/LoadingButton/Container.story.js
  src/components/LoadingButton/__snapshots__/Container.spec.js.snap
  src/components/LoadingButton/components/LoadingButton/__snapshots__/index.spec.js.snap
  src/components/LoadingButton/components/LoadingButton/index.js
  src/components/LoadingButton/components/LoadingButton/index.spec.js
  src/components/LoadingButton/components/LoadingIcon/__snapshots__/index.spec.js.snap
  src/components/LoadingButton/components/LoadingIcon/index.js
  src/components/LoadingButton/components/LoadingIcon/index.spec.js
  src/components/LoadingButton/components/icons/success.svg
  src/components/LoadingButton/constants.js
  src/components/LoadingButton/index.js
  src/components/LoadingButton/utils.js
  src/components/LoadingButton/utils.spec.js
  src/components/Spinner/Spinner.js
  src/components/Spinner/Spinner.spec.js
  src/components/Spinner/Spinner.story.js
  src/components/Spinner/__snapshots__/Spinner.spec.js.snap
  src/components/Spinner/icons/spinner.svg
  src/components/Spinner/index.js
  src/index.js
  src/util/fp.js
Labels: ready for review

#180 Enable italic Text
  src/components/Heading/Heading.js
  src/components/Heading/__snapshots__/Heading.spec.js.snap
  src/components/Markdown/__snapshots__/Markdown.spec.js.snap
  src/components/Text/Text.js
  src/components/Text/Text.spec.js
  src/components/Text/Text.story.js
  src/components/Text/__snapshots__/Text.spec.js.snap
Labels: enhancement, ready for review
