Repository sumup-oss/circuit-ui, pull requests merged in 2018-07, with the labels that each got.

#217 Add horizontal rule (Hr) component
  src/components/Hr/Hr.js
  src/components/Hr/Hr.spec.js
  src/components/Hr/Hr.story.js
  src/components/Hr/__snapshots__/Hr.spec.js.snap
  src/components/Hr/index.js
  src/index.js
Labels: enhancement, ready for review

#224 Move Modal z-index to theme
  src/components/Modal/Modal.js
  src/themes/default.js
Labels: enhancement, ready for review

#218 Add default bottom spacing to List
  src/components/List/List.js
  src/components/List/List.spec.js
  src/components/List/__snapshots__/List.spec.js.snap
Labels: enhancement, ready for review

#220 Add support for colored Badge component
  src/components/Badge/Badge.js
  src/components/Badge/Badge.spec.js
  src/components/Badge/Badge.story.js
  src/components/Badge/__snapshots__/Badge.spec.js.snap
  src/styles/constants.js
  src/util/constants.js
Labels: ready for review

#228 Ensure ButtonGroup can be styled
  src/components/ButtonGroup/ButtonGroup.js
Labels: enhancement

#229 Rollback react-text-mask to fixed version due to PureComponent bug
  package.json
  yarn.lock
Labels: bug, ready for review

#216 Add Blockquote component
  src/components/Blockquote/Blockquote.js
  src/components/Blockquote/Blockquote.spec.js
  src/components/Blockquote/Blockquote.story.js
  src/components/Blockquote/__snapshots__/Blockquote.spec.js.snap
  src/components/Blockquote/index.js
  src/index.js
Labels: enhancement, ready for review

#230 [BUG] Forward additional props to the Button
  src/components/Button/Button.js
  src/components/Button/constants.js
  src/components/LoadingButton/components/LoadingButton/__snapshots__/index.spec.js.snap
Labels: bug, ready for review

#232 [Tech] Add github url and change title for storybook
  .storybook/config.js
Labels: tech

#233 [ProgressBar] Fix rounding styles when progress is 100%
  src/components/ProgressBar/ProgressBar.js
  src/components/ProgressBar/ProgressBar.story.js
  src/components/ProgressBar/__snapshots__/ProgressBar.spec.js.snap
Labels: bug, ready for review

#239 Replace android pay logo with google pay
  src/components/CardSchemes/__snapshots__/CardSchemes.spec.js.snap
  src/components/CreditCardDetails/components/scheme-icons/card-scheme-icons.js
  src/components/CreditCardDetails/components/scheme-icons/icons/android-pay.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/google-pay.svg
Labels: ready for review

#240 Fix type helper for headings
  src/styles/style-helpers.js
Labels: bug, ready for review

#236 Add option to center align ButtonGroup
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/ButtonGroup.spec.js
  src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.js.snap
Labels: enhancement, ready for review

#235 Make font sizes responsive
  src/components/Blockquote/__snapshots__/Blockquote.spec.js.snap
  src/components/Button/components/PlainButton/__snapshots__/PlainButton.spec.js.snap
  src/components/Heading/Heading.js
  src/components/Heading/Heading.story.js
  src/components/Heading/__snapshots__/Heading.spec.js.snap
  src/components/Markdown/__snapshots__/Markdown.spec.js.snap
  src/components/SubHeading/SubHeading.js
  src/components/SubHeading/SubHeading.story.js
  src/components/Text/Text.js
  src/components/Text/Text.story.js
  src/components/Text/__snapshots__/Text.spec.js.snap
Labels: enhancement, ready for review

#249 Ensure (Regular)Button text is always centered
  src/components/Button/components/RegularButton/RegularButton.js
  src/components/Button/components/RegularButton/__snapshots__/RegularButton.spec.js.snap
  src/components/LoadingButton/__snapshots__/Container.spec.js.snap
  src/components/LoadingButton/components/LoadingButton/__snapshots__/index.spec.js.snap
Labels: bug, ready for review

#248 Limit width of cardscheme icons on IE
  src/components/CardSchemes/__snapshots__/CardSchemes.spec.js.snap
  src/components/CardSchemes/components/PaymentMethodIcon/PaymentMethodIcon.js
  src/components/CardSchemes/components/PaymentMethodIcon/__snapshots__/PaymentMethodIcon.spec.js.snap
Labels: bug, ready for review

#247 Contain SVG in Image component
  src/components/Image/Image.js
  src/components/Image/__snapshots__/Image.spec.js.snap
  src/components/Markdown/__snapshots__/Markdown.spec.js.snap
Labels: bug, ready for review

#246 Improve ButtonGroup stacking on mobile
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/ButtonGroup.story.js
  src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.js.snap
Labels: bug, ready for review

#241 Fix media queries and upgrade Emotion
  package.json
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/TableBody/__snapshots__/index.spec.js.snap
  src/components/Table/components/TableHead/__snapshots__/index.spec.js.snap
  src/styles/style-helpers.js
  yarn.lock
Labels: bug, ready for review, tech

#165 Rename theme to 'circuit'
  .storybook/config.js
  build/global-styles
  build/stylesheet/lib/extract-styles.js
  jest.setup.js
  src/components/AutoCompleteInput/AutoCompleteInput.js
  src/components/Col/Col.story.js
  src/components/CreditCardDetails/components/CardNumberInput/CardNumberInput.story.js
  src/components/Grid/Grid.story.js
  src/components/Popover/Popover.js
  src/components/Row/Row.story.js
  src/themes/circuit.js
  src/themes/index.js
Labels: enhancement, ready for review
