Repository sumup-oss/circuit-ui, pull requests merged in 2019-10, with the labels that each got.

#484 feat(styles): Update colors
  docs/content/styles/colors.mdx
  src/themes/circuit.js
Labels: ready for review

#488 fix(configs): automatically deploy Storybook and Docz from CI
  .storybook/webpack.config.js
  .travis.yml
  package.json
Labels: bug, tech

#489 feat(components): add mobile styles for Messages
  src/components/Message/Message.js
  src/components/Message/__snapshots__/Message.spec.js.snap
  src/components/Message/components/Button/Button.js
  src/components/Message/components/Button/__snapshots__/Button.spec.js.snap
  src/components/Message/components/Icon/Icon.js
  src/components/Message/components/Icon/__snapshots__/Icon.spec.js.snap
Labels: design, ready for review

#492 fix(components): pass href to NavItem link
  src/components/ButtonGroup/ButtonGroup.js
  src/components/Sidebar/components/NavItem/NavItem.js
  src/components/Sidebar/components/NavItem/__snapshots__/NavItem.spec.js.snap
  src/util/shared-prop-types.js
Labels: bug, ready for review

#499 fix(components): fix Sidebar NavItem bug on Safari
  src/components/Sidebar/components/NavItem/NavItem.js
  src/components/Sidebar/components/NavItem/__snapshots__/NavItem.spec.js.snap
Labels: bug, ready for review

#500 fix(docs): update favicon path
  docs/index.html
Labels: bug

#498 feat(tests): configure StoryShots
  .babelrc
  .storybook/.babelrc
  .storybook/config.js
  jest.config.js
  jest.mdxTransformer.js
  package.json
  src/__snapshots__/storyshots.spec.js.snap
  src/components/IconButton/IconButton.story.js
  src/storyshots.spec.js
  yarn.lock
Labels: ready for review, tech

#505 fix(scripts): prevent Storybook from overwriting the static CSS
  package.json
Labels: bug

#506 fix(components): fix Sidebar Footer padding bug on Safari
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Sidebar/Sidebar.story.js
  src/components/Sidebar/components/Footer/Footer.js
  src/components/Sidebar/components/Footer/__snapshots__/Footer.spec.js.snap
Labels: bug, ready for review
