Repository sumup-oss/circuit-ui, pull requests merged in 2019-02, with the labels that each got.

#374 Create new Sidebar component
  package.json
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/Sidebar.spec.js
  src/components/Sidebar/Sidebar.story.js
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/Backdrop/Backdrop.js
  src/components/Sidebar/components/Backdrop/Backdrop.spec.js
  src/components/Sidebar/components/Backdrop/__snapshots__/Backdrop.spec.js.snap
  src/components/Sidebar/components/Backdrop/index.js
  src/components/Sidebar/components/CloseButton/CloseButton.js
  src/components/Sidebar/components/CloseButton/CloseButton.spec.js
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Sidebar/components/CloseButton/closeIcon.svg
  src/components/Sidebar/components/CloseButton/index.js
  src/components/Sidebar/components/Header/Header.js
  src/components/Sidebar/components/Header/Header.spec.js
  src/components/Sidebar/components/Header/__snapshots__/Header.spec.js.snap
  src/components/Sidebar/components/Header/index.js
  src/components/Sidebar/components/NavItem/NavItem.js
  src/components/Sidebar/components/NavItem/NavItem.spec.js
  src/components/Sidebar/components/NavItem/__snapshots__/NavItem.spec.js.snap
  src/components/Sidebar/components/NavItem/index.js
  src/components/Sidebar/components/NavList/NavList.js
  src/components/Sidebar/components/NavList/NavList.spec.js
  src/components/Sidebar/components/NavList/__snapshots__/NavList.spec.js.snap
  src/components/Sidebar/components/NavList/index.js
  src/components/Sidebar/index.js
  src/index.js
  src/themes/circuit.js
Labels: ready for review

#375 Create AppBar component and SidebarContext to control toggling inside circuit
  package.json
  src/components/Hamburger/Hamburger.js
  src/components/Hamburger/Hamburger.story.js
  src/components/Hamburger/__snapshots__/Hamburger.spec.js.snap
  src/components/Header/Header.js
  src/components/Header/Header.spec.js
  src/components/Header/Header.story.js
  src/components/Header/__snapshots__/Header.spec.js.snap
  src/components/Header/components/Title/Title.js
  src/components/Header/components/Title/Title.spec.js
  src/components/Header/components/Title/__snapshots__/Title.spec.js.snap
  src/components/Header/components/Title/index.js
  src/components/Header/index.js
  src/components/Sidebar/SidebarContext.js
  src/components/Sidebar/SidebarContext.spec.js
  src/components/Sidebar/index.js
  src/index.js
Labels: ready for review

#376 Add strike through option to Text
  src/components/Text/Text.js
  src/components/Text/Text.spec.js
  src/components/Text/Text.story.js
  src/components/Text/__snapshots__/Text.spec.js.snap
Labels: enhancement, ready for review

#377 Make Header sticky and increase Sidebar breakpoints for better screen fit
  src/components/Header/Header.js
  src/components/Header/__snapshots__/Header.spec.js.snap
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/Backdrop/Backdrop.js
  src/components/Sidebar/components/Backdrop/__snapshots__/Backdrop.spec.js.snap
  src/components/Sidebar/components/CloseButton/CloseButton.js
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/themes/circuit.js
Labels: ready for review

#378 [TECH] Remove css source maps from build
  .babelrc
Labels: ready for review, tech

#383 Add titles to card scheme icons
  src/components/CreditCardDetails/components/scheme-icons/icons/apple-pay.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/banco-estado.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/cash.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/dankort.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/elo.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/google-pay.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/hiper.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/jcb.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/nfc.svg
  src/components/CreditCardDetails/components/scheme-icons/icons/union-pay.svg
Labels: bug, ready for review

#384 Make Sidebar close on backdrop click
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/Sidebar.spec.js
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
Labels: ready for review
