Repository sumup-oss/circuit-ui, pull requests merged in 2019-09, with the labels that each got.

#465 fix(components): center align text inside Badge
  src/components/Badge/Badge.js
  src/components/Badge/__snapshots__/Badge.spec.js.snap
Labels: bug, design, ready for review

#473 fix(components): sort Table rows with nested cells
  src/components/Table/Table.js
  src/components/Table/utils.js
  src/components/Table/utils.spec.js
Labels: bug, ready for review

#475 fix(components): minor fixes for ListItem, Tabs and Table components
  src/components/CardList/__snapshots__/CardList.spec.js.snap
  src/components/CardList/components/Item/Item.js
  src/components/Table/components/TableRow/TableRow.js
  src/components/Table/components/TableRow/__snapshots__/TableRow.spec.js.snap
  src/components/Tabs/__snapshots__/Tabs.spec.js.snap
  src/components/Tabs/components/Tab/Tab.js
  src/components/Tabs/components/Tab/__snapshots__/Tab.spec.js.snap
Labels: bug, ready for review

#456 docs: second review on components
  docs/content/components/button.mdx
  docs/content/components/sidebar.mdx
  docs/content/principles.mdx
Labels: in progress

#472 test(configs): include SVG props in snapshots
  jest.fileTransformer.js
  src/components/AutoCompleteInput/__snapshots__/AutoCompleteInput.spec.js.snap
  src/components/AutoCompleteTags/__snapshots__/AutoCompleteTags.spec.js.snap
  src/components/CardSchemes/__snapshots__/CardSchemes.spec.js.snap
  src/components/CardSchemes/components/PaymentMethodIcon/__snapshots__/PaymentMethodIcon.spec.js.snap
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
  src/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/CreditCardDetails/components/CardNumberInput/__snapshots__/CardNumberInput.spec.js.snap
  src/components/InfoIcon/InfoIcon.js
  src/components/InfoIcon/__snapshots__/InfoIcon.spec.js.snap
  src/components/Input/__snapshots__/Input.spec.js.snap
  src/components/LoadingButton/__snapshots__/LoadingButton.spec.js.snap
  src/components/LoadingButton/components/Button/__snapshots__/Button.spec.js.snap
  src/components/LoadingButton/components/LoadingIcon/__snapshots__/LoadingIcon.spec.js.snap
  src/components/Message/components/Icon/__snapshots__/Icon.spec.js.snap
  src/components/SearchInput/__snapshots__/SearchInput.spec.js.snap
  src/components/Select/__snapshots__/Select.spec.js.snap
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Spinner/__snapshots__/Spinner.spec.js.snap
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/SortArrow/__snapshots__/SortArrow.spec.js.snap
  src/components/Table/components/TableHead/__snapshots__/TableHead.spec.js.snap
  src/components/Table/components/TableHeader/__snapshots__/TableHeader.spec.js.snap
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
Labels: ready for review

#480 fix(utils): Fix storybook __DEV__ exception
  .storybook/webpack.config.js
Labels: bug, ready for review
