Repository sumup-oss/circuit-ui, pull requests merged in 2019-01, with the labels that each got.

#358 Update emotion integration with docz
  docs/utils/Wrapper.js
  doczrc.js
Labels: bug

#360 (chore) Remove symlink files that are no longer used
  doczrc.js
  styles.js
  themes.js
  utils.js
Labels: enhancement, ready for review

#363 (fix) Fix checkbox's checkmark not showing on Safari
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
  src/components/Checkbox/checked-icon.svg
Labels: bug, ready for review

#366 (bugfix) Fix theme import in docz
  docs/content/styles/components/Swatch.js
  docs/utils/PropTable.js
Labels: bug, ready for review

#368 (bugfix) Repair babel config for static style extraction
  .babelrc
  docs/content/styles/components/Swatch.js
  package.json
  src/styles/global-styles.js
Labels: bug, ready for review

#362 (chore) Upgrade Foundry to v1
  .eslintrc.js
  .huskyrc.js
  lint-staged.config.js
  package.json
  plopfile.js
  prettier.config.js
  src/components/AutoCompleteInput/AutoCompleteInput.js
  src/components/Badge/Badge.js
  src/components/Button/Button.story.js
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/ButtonGroup.story.js
  src/components/CalendarTag/CalendarTag.js
  src/components/CalendarTagTwoStep/CalendarTagTwoStep.js
  src/components/Card/Card.js
  src/components/Col/utils.js
  src/components/Heading/Heading.js
  src/components/HtmlElement/HtmlElement.js
  src/components/InlineElements/InlineElements.js
  src/components/InlineNotification/InlineNotification.js
  src/components/Input/Input.js
  src/components/List/List.js
  src/components/LoadingButton/Container.js
  src/components/Modal/Modal.spec.js
  src/components/Modal/Modal.story.js
  src/components/Pagination/PaginationService.js
  src/components/Picture/Picture.js
  src/components/Popover/Popover.js
  src/components/Popover/Popover.spec.js
  src/components/Portal/Portal.js
  src/components/Price/PriceService.js
  src/components/ProgressBar/ProgressBar.js
  src/components/ProgressBar/ProgressBar.story.js
  src/components/Select/Select.story.js
  src/components/State/State.js
  src/components/SubHeading/SubHeading.js
  src/components/Table/Table.js
  src/components/Tag/Tag.js
  src/components/Text/Text.js
  src/components/Tooltip/Tooltip.js
  templates/component/Component.js
  templates/component/Component.spec.js
  templates/component/Component.story.js
  templates/component/index.js
  yarn.lock
Labels: ready for review, tech

#370 v0.0.20-canary
  package.json
Labels: ready for review

#371 (bugfix) Fix theme import in docs once and for all
  docs/content/component-status/components/Statuses.js
  docs/content/components/DocButton.js
  docs/content/getting-started/developers.mdx
  docs/content/styles/components/BorderRadius.js
  docs/content/styles/components/BorderWidth.js
  docs/content/styles/components/IconSize.js
  docs/content/styles/components/MediaQueriesTable.js
  docs/content/styles/components/Spacing.js
  docs/content/styles/components/Swatch.js
  docs/content/styles/components/Type.js
  docs/utils/PropTable.js
  docs/utils/Wrapper.js
Labels: bug, ready for review
