Repository sumup-oss/circuit-ui, pull requests merged in 2019-03, with the labels that each got.

#385 Fix default theme URL.
  docs/content/styles/theme-reference.mdx
Labels: bug, ready for review

#386 fix: Add label to CloseButton
  src/components/Card/components/Header/Header.js
  src/components/CloseButton/CloseButton.js
  src/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Modal/components/ModalHeader/ModalHeader.js
  src/components/Tag/Tag.js
  src/components/Tag/__snapshots__/Tag.spec.js.snap
Labels: bug, ready for review

#387 v0.0.24-canary
  package.json
Labels: ready for review

#359 Design documentation Pt. I
  docs/content/components/TooltipContainer.js
  docs/content/components/forms.mdx
  docs/content/components/list.mdx
  docs/content/components/modal.mdx
  docs/content/components/tooltip.mdx
  docs/content/styles/spacing.mdx
Labels: design, ready for review

#382 Tabs + Tab components
  src/components/Tabs/Tabs.js
  src/components/Tabs/Tabs.spec.js
  src/components/Tabs/Tabs.story.js
  src/components/Tabs/__snapshots__/Tabs.spec.js.snap
  src/components/Tabs/components/Element/Element.js
  src/components/Tabs/components/Element/Element.spec.js
  src/components/Tabs/components/Element/index.js
  src/components/Tabs/components/Tab/Tab.js
  src/components/Tabs/components/Tab/Tab.spec.js
  src/components/Tabs/components/Tab/__snapshots__/Tab.spec.js.snap
  src/components/Tabs/components/Tab/index.js
  src/components/Tabs/components/TabList/TabList.js
  src/components/Tabs/components/TabList/index.js
  src/components/Tabs/components/TabPanel/TabPanel.js
  src/components/Tabs/components/TabPanel/index.js
  src/components/Tabs/components/TabPanels/TabPanels.js
  src/components/Tabs/components/TabPanels/index.js
  src/components/Tabs/index.js
  src/index.js
  src/util/fp.js
  src/util/key-codes.js
Labels: enhancement

#388 [SA-2377] Pagination improvements
  src/components/Button/components/RegularButton/RegularButton.js
  src/components/Pagination/PageButton/PageButton.js
  src/components/Pagination/PageButton/__snapshots__/PageButton.spec.js.snap
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.story.js
  src/components/Pagination/PaginationContainer/PaginationContainer.js
  src/components/Pagination/PaginationContainer/__snapshots__/PaginationContainer.spec.js.snap
  src/components/Pagination/Separator/Ellipsis.js
  src/components/Pagination/Separator/index.js
  src/components/Pagination/__snapshots__/Pagination.spec.js.snap
  src/styles/style-helpers.js
Labels: ready for review

#389 Add fallback for unsupported currencies
  src/util/__snapshots__/currency.spec.js.snap
  src/util/currency.js
  src/util/currency.spec.js
Labels: enhancement

#390 Create Footer component for the Sidebar
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/Sidebar.story.js
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/CloseButton/CloseButton.js
  src/components/Sidebar/components/Footer/Footer.js
  src/components/Sidebar/components/Footer/Footer.spec.js
  src/components/Sidebar/components/Footer/__snapshots__/Footer.spec.js.snap
  src/components/Sidebar/components/Footer/index.js
  src/components/Sidebar/components/Header/Header.js
Labels: ready for review
