Repository sumup-oss/circuit-ui, pull requests merged in 2019-04, with the labels that each got.

#393 Export additional table components
  src/components/Table/index.js
  src/index.js
Labels: ready for review, tech

#336 Move react-modal overflow to html instead of body
  package.json
  src/components/Modal/Modal.js
  yarn.lock
Labels: bug, ready for review

#395 Fix Hamburger styles on IE11
  src/components/Hamburger/Hamburger.js
  src/components/Hamburger/__snapshots__/Hamburger.spec.js.snap
Labels: bug, ready for review

#398 Add Red Compra card scheme icon
  src/components/CardSchemes/__snapshots__/CardSchemes.spec.js.snap
  src/components/CreditCardDetails/components/scheme-icons/card-scheme-icons.js
  src/components/CreditCardDetails/components/scheme-icons/icons/red-compra.svg
Labels: enhancement, ready for review
