Repository sumup-oss/circuit-ui, pull requests merged in 2019-05, with the labels that each got.

#397 Preserve Tag selected styles on hover
  src/components/Tag/Tag.js
Labels: bug, ready for review

#404 Add fixed width/height for Table sorting arrows
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/SortArrow/__snapshots__/index.spec.js.snap
  src/components/Table/components/SortArrow/index.js
  src/components/Table/components/TableHead/__snapshots__/index.spec.js.snap
  src/components/Table/components/TableHead/index.js
  src/components/Table/components/TableHeader/__snapshots__/index.spec.js.snap
Labels: bug, ready for review

#403 Update mega font-size to prevent input zoom on iOS
  src/components/AutoCompleteInput/__snapshots__/AutoCompleteInput.spec.js.snap
  src/components/AutoCompleteTags/__snapshots__/AutoCompleteTags.spec.js.snap
  src/components/Blockquote/__snapshots__/Blockquote.spec.js.snap
  src/components/Button/components/PlainButton/__snapshots__/PlainButton.spec.js.snap
  src/components/Button/components/RegularButton/__snapshots__/RegularButton.spec.js.snap
  src/components/Calendar/__snapshots__/RangePicker.spec.js.snap
  src/components/Calendar/__snapshots__/SingleDayPicker.spec.js.snap
  src/components/Calendar/components/CalendarWrapper/__snapshots__/CalendarWrapper.spec.js.snap
  src/components/CalendarTag/__snapshots__/CalendarTag.spec.js.snap
  src/components/CalendarTagTwoStep/__snapshots__/CalendarTagTwoStep.spec.js.snap
  src/components/CreditCardDetails/components/CardNumberInput/__snapshots__/CardNumberInput.spec.js.snap
  src/components/CurrencyInput/components/SimpleCurrencyInput/__snapshots__/SimpleCurrencyInput.spec.js.snap
  src/components/Input/__snapshots__/Input.spec.js.snap
  src/components/List/__snapshots__/List.spec.js.snap
  src/components/LoadingButton/__snapshots__/Container.spec.js.snap
  src/components/LoadingButton/components/LoadingButton/__snapshots__/index.spec.js.snap
  src/components/Markdown/__snapshots__/Markdown.spec.js.snap
  src/components/Pagination/PageButton/__snapshots__/PageButton.spec.js.snap
  src/components/SearchInput/__snapshots__/SearchInput.spec.js.snap
  src/components/Select/__snapshots__/Select.spec.js.snap
  src/components/Tabs/__snapshots__/Tabs.spec.js.snap
  src/components/Tabs/components/Tab/__snapshots__/Tab.spec.js.snap
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/components/Text/__snapshots__/Text.spec.js.snap
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
  src/themes/circuit.js
Labels: bug, design, ready for review

#405 Add type to Switch to prevent form actions being dispatched
  src/components/Toggle/__snapshots__/Toggle.spec.js.snap
  src/components/Toggle/components/Switch/Switch.js
  src/components/Toggle/components/Switch/__snapshots__/Switch.spec.js.snap
Labels: bug, ready for review

#406 Add possibility for second level navigation on the Sidebar
  src/components/Sidebar/Sidebar.story.js
  src/components/Sidebar/components/Header/Header.js
  src/components/Sidebar/components/Header/__snapshots__/Header.spec.js.snap
  src/components/Sidebar/components/NavItem/NavItem.js
  src/components/Sidebar/components/NavItem/NavItem.spec.js
  src/components/Sidebar/components/NavItem/__snapshots__/NavItem.spec.js.snap
  src/components/Sidebar/components/NavItem/utils.js
  src/components/Sidebar/components/NavItem/utils.spec.js
  src/components/Sidebar/components/SubNavList/SubNavList.js
  src/components/Sidebar/components/SubNavList/SubNavList.spec.js
  src/components/Sidebar/components/SubNavList/__snapshots__/SubNavList.spec.js.snap
  src/components/Sidebar/components/SubNavList/index.js
  src/components/Sidebar/components/SubNavList/utils.js
  src/components/Sidebar/components/SubNavList/utils.spec.js
  src/util/type-check.js
Labels: ready for review

#408 Fix Sidebar styles to match new design constraints
  src/components/Sidebar/components/NavItem/NavItem.js
  src/components/Sidebar/components/NavItem/__snapshots__/NavItem.spec.js.snap
  src/components/Sidebar/components/SubNavList/SubNavList.js
  src/components/Sidebar/components/SubNavList/__snapshots__/SubNavList.spec.js.snap
Labels: ready for review
