Repository sumup-oss/circuit-ui, pull requests merged in 2019-07, with the labels that each got.

#423 feat(components): add prop forwarding support to TableRows
  src/components/Table/Table.js
  src/components/Table/Table.story.js
  src/components/Table/components/TableBody/index.js
  src/components/Table/components/TableBody/index.spec.js
  src/components/Table/components/TableHead/index.js
  src/components/Table/utils.js
  src/components/Table/utils.spec.js
Labels: enhancement, ready for review

#425 docs: Remove outdated changelog and link to GitHub.
  docs/content/changelog.mdx
Labels: ready for review

#429 fix(components): Correctly pass styles from Textarea to Input
  src/components/TextArea/TextArea.js
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
Labels: bug, ready for review

#430 fix(components): add position relative styles to Table container
  src/components/Table/Table.js
  src/components/Table/__snapshots__/Table.spec.js.snap
Labels: bug, ready for review

#431 fix(components): add missing font-styles to table fixed row headers
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/TableCell/index.js
Labels: bug, ready for review

#428 feat: Implement LoadingButton error state
  src/components/LoadingButton/Container.spec.js
  src/components/LoadingButton/Container.story.js
  src/components/LoadingButton/__snapshots__/Container.spec.js.snap
  src/components/LoadingButton/components/LoadingButton/__snapshots__/index.spec.js.snap
  src/components/LoadingButton/components/LoadingIcon/__snapshots__/index.spec.js.snap
  src/components/LoadingButton/components/LoadingIcon/index.js
  src/components/LoadingButton/components/LoadingIcon/index.spec.js
  src/components/LoadingButton/components/icons/error.svg
Labels: enhancement, ready for review

#433 feat(mobile-header): add mobileOnly prop to Header
  src/components/Header/Header.js
  src/components/Header/Header.spec.js
  src/components/Header/Header.story.js
  src/components/Header/__snapshots__/Header.spec.js.snap
Labels: ready for review

#426 docs: Create contribution guidelines and update docs
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/suggest-tech-improvement.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/component-addition-flowchart.png
  docs/404.html
  docs/content/changelog.mdx
  docs/content/component-status/components/Statuses.js
  docs/content/component-status/index.mdx
  docs/content/components/DocButton.js
  docs/content/components/badge.mdx
  docs/content/components/blockquote.mdx
  docs/content/components/button.js
  docs/content/components/button.mdx
  docs/content/components/calendar.js
  docs/content/components/calendar.mdx
  docs/content/components/card-schemes.mdx
  docs/content/components/card.mdx
  docs/content/components/date-picker.mdx
  docs/content/components/forms.mdx
  docs/content/components/hr.mdx
  docs/content/components/image.mdx
  docs/content/components/inline-notification.mdx
  docs/content/components/list.mdx
  docs/content/components/markdown.mdx
  docs/content/components/message.mdx
  docs/content/components/modal.mdx
  docs/content/components/pagination.mdx
  docs/content/components/progress-bar.mdx
  docs/content/components/selector.js
  docs/content/components/selector.mdx
  docs/content/components/sidebar.js
  docs/content/components/sidebar.mdx
  docs/content/components/table.mdx
  docs/content/components/tabs.mdx
  docs/content/components/tag.mdx
  docs/content/components/toggle.mdx
  docs/content/components/tooltip.mdx
  docs/content/components/typography.mdx
  docs/content/getting-started/designers.mdx
  docs/content/getting-started/developers.mdx
  docs/content/getting-started/faq.mdx
  docs/content/getting-started/how-to-document.mdx
  docs/content/principles.mdx
  docs/content/styles/colors.mdx
  docs/content/styles/fonts.mdx
  docs/index.html
  docs/public/images/circuit-logo.png
  docs/utils/PropTable.js
  docs/utils/Statuses.js
  docs/utils/Wrapper.js
  docs/utils/service.js
  doczrc.js
  package.json
Labels: ready for review

#437 docs(docs): add sessionStorage redirect for page refresh
  docs/404.html
  docs/index.html
Labels: ready for review

#446 chore(configs): Temporarily disable security audit in CI
  .travis.yml
Labels: ready for review, tech

#443 feat(utils): Add deprecation helpers
  .babelrc
  package.json
  src/components/SideNav/components/Modal/Modal.js
  src/components/SideNav/transitions.js
  src/util/deprecate.js
  src/util/helpers.js
  src/util/shared-prop-types.js
  yarn.lock
Labels: enhancement, ready for review

#445 fix(components): Correctly apply TextArea styles
  src/components/Input/Input.js
  src/components/Input/Input.spec.js
  src/components/Input/__snapshots__/Input.spec.js.snap
  src/components/TextArea/TextArea.js
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
Labels: bug, ready for review

#444 fix(components): Force consistent height of Select across browsers
  src/components/Select/Select.js
  src/components/Select/__snapshots__/Select.spec.js.snap
Labels: bug, ready for review

#448 refactor(components): Use new props to pass styles to the Input
  src/components/CreditCardDetails/components/CardNumberInput/CardNumberInput.js
  src/components/CreditCardDetails/components/CardNumberInput/__snapshots__/CardNumberInput.spec.js.snap
  src/components/CurrencyInput/components/SimpleCurrencyInput/SimpleCurrencyInput.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/__snapshots__/SimpleCurrencyInput.spec.js.snap
Labels: enhancement, ready for review

#449 fix(utils): Check custom prop types correctly
  src/util/shared-prop-types.js
Labels: bug, ready for review

#452 feat(components): Add a validation hint to the Checkbox
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/Checkbox.spec.js
  src/components/Checkbox/Checkbox.story.js
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
Labels: enhancement, ready for review

#451 feat(components): Add a validation hint to the Select
  src/components/Input/Input.js
  src/components/Select/Select.js
  src/components/Select/Select.spec.js
  src/components/Select/Select.story.js
  src/components/Select/__snapshots__/Select.spec.js.snap
  src/components/Select/arrows.svg
  src/icons/arrows.svg
  src/icons/error.svg
  src/icons/valid.svg
  src/icons/warning.svg
Labels: enhancement, ready for review

#455 fix: Remove default props for deprecated props in Input
  src/components/AutoCompleteInput/__snapshots__/AutoCompleteInput.spec.js.snap
  src/components/AutoCompleteTags/__snapshots__/AutoCompleteTags.spec.js.snap
  src/components/CreditCardDetails/components/CardNumberInput/__snapshots__/CardNumberInput.spec.js.snap
  src/components/CurrencyInput/components/SimpleCurrencyInput/__snapshots__/SimpleCurrencyInput.spec.js.snap
  src/components/Input/Input.js
  src/components/Input/__snapshots__/Input.spec.js.snap
  src/components/SearchInput/__snapshots__/SearchInput.spec.js.snap
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
  src/util/deprecate.js
Labels: bug, ready for review

#457 fix(components): Position validation hint relative to Checkbox
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
Labels: bug, ready for review
