Repository sumup-oss/circuit-ui, pull requests merged in 2020-01, with the labels that each got.

#523 fix(components): sort layout columns by priority
  src/components/Col/utils.js
Labels: bug

#517 docs: rewrite contributing guidelines
  .github/CONTRIBUTING.md
  .storybook/components/Image.js
  .storybook/components/Intro.js
  .storybook/components/Link.js
  .storybook/components/Statuses.js
  .storybook/components/Swatch.js
  .storybook/components/Teaser.js
  .storybook/components/Type.js
  .storybook/components/index.js
  .storybook/config.js
  .storybook/util/theme.js
  .travis.yml
  README.md
  docs/advanced/components.story.mdx
  docs/advanced/fonts.story.mdx
  docs/advanced/grid.story.mdx
  docs/advanced/static-css.story.mdx
  docs/advanced/theme.story.mdx
  docs/introduction/code-of-conduct.story.mdx
  docs/introduction/contributing.story.mdx
  docs/introduction/design-principles.story.mdx
  docs/introduction/developers.story.mdx
  docs/introduction/getting-started.story.mdx
  docs/introduction/welcome.story.mdx
  docs/styles/colors.story.mdx
  docs/styles/media-queries.story.mdx
  docs/styles/spacing.story.mdx
  docs/styles/theme.story.mdx
  docs/styles/typography.story.mdx
  package.json
  yarn.lock
Labels: ready for review

#522 fix: Move minus symbol in front of the currency symbol
  src/util/currency.js
  src/util/currency.spec.js
Labels: bug

#531 fix(components): prevent background from scrolling when modal is open
  src/components/Modal/Modal.js
  src/components/Modal/ModalProvider.js
Labels: bug, ready for review

#532 fix: adds Select margin top when label above
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Select/Select.js
  src/components/Select/Select.story.js
  src/components/Select/__snapshots__/Select.spec.js.snap
Labels: bug

#542 fix(components): remove scrollbar from LoadingButton
  src/__snapshots__/storyshots.spec.js.snap
  src/components/LoadingButton/LoadingButton.story.js
  src/components/LoadingButton/__snapshots__/LoadingButton.spec.js.snap
  src/components/LoadingButton/components/Button/Button.js
  src/components/LoadingButton/components/Button/__snapshots__/Button.spec.js.snap
  src/components/LoadingButton/components/LoadingIcon/LoadingIcon.js
Labels: bug
