Repository sumup-oss/circuit-ui, pull requests merged in 2020-07, with the labels that each got.

#598 tech: integration of collector
  .storybook/preview.js
  docs/advanced/tracking.story.mdx
  package.json
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Button/Button.story.tsx
  src/components/Button/Button.tsx
  src/components/CalendarTag/CalendarTag.js
  src/components/CalendarTag/CalendarTag.story.js
  src/components/CalendarTagTwoStep/CalendarTagTwoStep.js
  src/components/CalendarTagTwoStep/CalendarTagTwoStep.story.js
  src/components/Card/Card.story.js
  src/components/Card/components/Header/Header.js
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/Checkbox.story.js
  src/components/Hamburger/Hamburger.story.tsx
  src/components/Hamburger/Hamburger.tsx
  src/components/Modal/Modal.story.tsx
  src/components/Modal/Modal.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/components/PageSelect/PageSelect.tsx
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/RadioButton.story.js
  src/components/Select/Select.story.tsx
  src/components/Select/Select.tsx
  src/components/Selector/Selector.story.tsx
  src/components/Selector/Selector.tsx
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/Sidebar.story.js
  src/components/Sidebar/components/NavItem/NavItem.js
  src/components/Tag/Tag.js
  src/components/Tag/Tag.story.js
  src/components/Toggle/Toggle.story.js
  src/components/Toggle/components/Switch/Switch.js
  src/hooks/use-click-handler.spec.ts
  src/hooks/use-click-handler.tsx
  yarn.lock
Labels: RFC, feature

#625 refactor(components): migrate Checkbox to TypeScript
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Checkbox/Checkbox.docs.mdx
  src/components/Checkbox/Checkbox.spec.tsx
  src/components/Checkbox/Checkbox.story.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
  src/components/Checkbox/index.ts
Labels: feature

#628 feat(components): migrate Toggle to TypeScript
  MIGRATION.md
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/cli/migrate/__testfixtures__/toggle-checked-prop.input.js
  src/cli/migrate/__testfixtures__/toggle-checked-prop.output.js
  src/cli/migrate/__tests__/transforms.spec.js
  src/cli/migrate/toggle-checked-prop.ts
  src/components/Toggle/Toggle.docs.mdx
  src/components/Toggle/Toggle.spec.tsx
  src/components/Toggle/Toggle.story.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/__snapshots__/Toggle.spec.tsx.snap
  src/components/Toggle/components/Switch/Switch.spec.tsx
  src/components/Toggle/components/Switch/Switch.tsx
  src/components/Toggle/components/Switch/__snapshots__/Switch.spec.tsx.snap
  src/components/Toggle/components/Switch/index.js
  src/components/Toggle/components/index.js
  src/components/Toggle/index.ts
Labels: feature

#631 feat(utils): add Colombia number and currency formats
  src/util/currency.js
  src/util/currency.spec.js
  src/util/numbers.js
  src/util/numbers.spec.js
Labels: feature

#634 fix(components): remove Input focus outline
  src/__snapshots__/storyshots.spec.js.snap
  src/components/CurrencyInput/__snapshots__/CurrencyInput.spec.tsx.snap
  src/components/Input/Input.tsx
  src/components/Input/__snapshots__/Input.spec.tsx.snap
  src/components/SearchInput/__snapshots__/SearchInput.spec.tsx.snap
  src/components/Select/Select.tsx
  src/components/TextArea/__snapshots__/TextArea.spec.tsx.snap
Labels: bug

#629 chore(ci): add CodeQL analysis workflow
  .github/workflows/codeql-analysis.yml
Labels: tech

#638 feat(components): add tracking to Carousel component
  .storybook/preview.js
  src/components/Carousel/Carousel.js
  src/components/Step/Step.js
  src/components/Step/hooks/use-step.js
Labels: feature

#639 fix(components): fix cross browser inconsistencies
  .storybook/main.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Calendar/RangePicker.story.js
  src/components/Calendar/SingleDayPicker.story.js
  src/components/Calendar/__snapshots__/RangePicker.spec.js.snap
  src/components/Calendar/__snapshots__/SingleDayPicker.spec.js.snap
  src/components/Calendar/calendar.story.mdx
  src/components/Calendar/components/CalendarWrapper/CalendarImportedStyles.js
  src/components/Calendar/components/CalendarWrapper/CalendarWrapper.js
  src/components/Calendar/components/CalendarWrapper/__snapshots__/CalendarWrapper.spec.js.snap
  src/components/CalendarTag/CalendarTag.story.js
  src/components/CalendarTagTwoStep/CalendarTagTwoStep.story.js
  src/components/Card/Card.story.js
  src/components/Checkbox/Checkbox.story.tsx
  src/components/CurrencyInput/__snapshots__/CurrencyInput.spec.tsx.snap
  src/components/Input/Input.tsx
  src/components/Input/__snapshots__/Input.spec.tsx.snap
  src/components/SearchInput/__snapshots__/SearchInput.spec.tsx.snap
  src/components/TextArea/__snapshots__/TextArea.spec.tsx.snap
  yarn.lock
Labels: bug

#640 fix(configs): restore IE11 compatibility
  .storybook/main.js
  package.json
Labels: bug

#641 feat(cli): add codemods for theme changes
  MIGRATION.md
  src/cli/migrate/__testfixtures__/theme-grid-tera.input.js
  src/cli/migrate/__testfixtures__/theme-grid-tera.output.js
  src/cli/migrate/__testfixtures__/theme-icon-sizes.input.js
  src/cli/migrate/__testfixtures__/theme-icon-sizes.output.js
  src/cli/migrate/__testfixtures__/theme-to-design-tokens-1.input.js
  src/cli/migrate/__testfixtures__/theme-to-design-tokens-1.output.js
  src/cli/migrate/__testfixtures__/theme-to-design-tokens-2.input.js
  src/cli/migrate/__testfixtures__/theme-to-design-tokens-2.output.js
  src/cli/migrate/__tests__/transforms.spec.js
  src/cli/migrate/theme-grid-tera.ts
  src/cli/migrate/theme-icon-sizes.ts
  src/cli/migrate/theme-to-design-tokens.ts
Labels: feature

#642 feat(cli): write codemod for currency utils
  src/cli/migrate/__testfixtures__/currency-utils-1.input.js
  src/cli/migrate/__testfixtures__/currency-utils-1.output.js
  src/cli/migrate/__testfixtures__/currency-utils-2.input.js
  src/cli/migrate/__testfixtures__/currency-utils-2.output.js
  src/cli/migrate/__tests__/transforms.spec.js
  src/cli/migrate/currency-utils.ts
Labels: feature

#643 fix(cli): rename intl-js import to intl for currency-utils codemod
  MIGRATION.md
  src/cli/migrate/__testfixtures__/currency-utils-1.output.js
  src/cli/migrate/__testfixtures__/currency-utils-2.output.js
  src/cli/migrate/currency-utils.ts
Labels: bug

#644 fix(cli): rename formatAmountForLocale to format for currency-utils
  src/cli/migrate/__testfixtures__/currency-utils-1.output.js
  src/cli/migrate/__testfixtures__/currency-utils-2.output.js
  src/cli/migrate/currency-utils.ts
Labels: bug

#647 fix(components): use custom JSX pragma from Emotion
  .eslintrc.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.spec.tsx.snap
  src/components/Card/Card.story.js
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/Carousel/components/Buttons/__snapshots__/Buttons.spec.js.snap
  src/components/CloseButton/CloseButton.tsx
  src/components/CloseButton/__snapshots__/CloseButton.spec.tsx.snap
  src/components/CurrencyInput/CurrencyInput.story.tsx
  src/components/CurrencyInput/__snapshots__/CurrencyInput.spec.tsx.snap
  src/components/Hamburger/__snapshots__/Hamburger.spec.tsx.snap
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/__snapshots__/IconButton.spec.tsx.snap
  src/components/Input/Input.story.tsx
  src/components/Input/Input.tsx
  src/components/Input/__snapshots__/Input.spec.tsx.snap
  src/components/LoadingButton/LoadingButton.tsx
  src/components/LoadingButton/__snapshots__/LoadingButton.spec.tsx.snap
  src/components/Modal/Modal.embed.story.tsx
  src/components/Modal/Modal.story.tsx
  src/components/Notification/Notification.story.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/__snapshots__/Notification.spec.tsx.snap
  src/components/NotificationBanner/NotificationBanner.story.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__snapshots__/Pagination.spec.tsx.snap
  src/components/ProgressBar/ProgressBar.story.tsx
  src/components/SearchInput/__snapshots__/SearchInput.spec.tsx.snap
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.spec.tsx.snap
  src/components/Sidebar/Sidebar.story.js
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Sidebar/components/NavItem/NavItem.js
  src/components/Spinner/Spinner.story.tsx
  src/components/Table/components/SortArrow/SortArrow.js
  src/components/Tag/Tag.js
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/components/TextArea/__snapshots__/TextArea.spec.tsx.snap
  src/components/ValidationHint/ValidationHint.tsx
  src/components/ValidationHint/__snapshots__/ValidationHint.spec.tsx.snap
  yarn.lock
Labels: bug

#648 fix(components): improve compatibility with IE11
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Carousel/components/Slide/Slide.story.js
  src/components/CurrencyInput/CurrencyInput.docs.mdx
  src/components/Pagination/__snapshots__/Pagination.spec.tsx.snap
  src/components/Pagination/components/PageSelect/__snapshots__/PageSelect.spec.tsx.snap
  src/components/ProgressBar/ProgressBar.story.tsx
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.spec.tsx.snap
Labels: bug

#649 fix(components): show focus outline around TableRow
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Table/Table.js
  src/components/Table/components/TableRow/TableRow.js
  src/components/Table/components/TableRow/__snapshots__/TableRow.spec.js.snap
  yarn.lock
Labels: bug

#650 fix(components): fix visual regressions
  src/__snapshots__/storyshots.spec.js.snap
  src/components/CalendarTag/__snapshots__/CalendarTag.spec.js.snap
  src/components/CalendarTagTwoStep/__snapshots__/CalendarTagTwoStep.spec.js.snap
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/ProgressBar/ProgressBar.tsx
  src/components/ProgressBar/__snapshots__/ProgressBar.spec.tsx.snap
  src/components/Selector/Selector.tsx
  src/components/Selector/__snapshots__/Selector.spec.tsx.snap
  src/components/SelectorGroup/__snapshots__/SelectorGroup.spec.tsx.snap
  src/components/Tabs/Tabs.story.js
  src/components/Tabs/__snapshots__/Tabs.spec.js.snap
  src/components/Tabs/components/TabList/TabList.js
  src/components/Tag/Tag.js
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/styles/style-helpers.spec.ts
  src/styles/style-helpers.ts
Labels: bug

#652 fix(components): pass styles to Selector and RadioButton label
  src/components/RadioButton/RadioButton.tsx
  src/components/Selector/Selector.tsx
Labels: bug

#651 feat(configs): move @sumup/collector to peer dependencies
  MIGRATION.md
  docs/introduction/getting-started.story.mdx
  package.json
Labels: feature

#653 docs: add missing sections to migration guide
  MIGRATION.md
  src/cli/migrate/__testfixtures__/onchange-prop.input.js
  src/cli/migrate/__testfixtures__/onchange-prop.output.js
  src/cli/migrate/onchange-prop.ts
Labels: documentation

#654 feat(components): migrate Tag to TypeScript
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Button/Button.tsx
  src/components/CalendarTag/__snapshots__/CalendarTag.spec.js.snap
  src/components/CalendarTagTwoStep/__snapshots__/CalendarTagTwoStep.spec.js.snap
  src/components/Input/Input.tsx
  src/components/Tag/Tag.docs.mdx
  src/components/Tag/Tag.js
  src/components/Tag/Tag.spec.tsx
  src/components/Tag/Tag.story.tsx
  src/components/Tag/Tag.tsx
  src/components/Tag/__snapshots__/Tag.spec.tsx.snap
  src/components/Tag/index.tsx
Labels: feature
