Repository sumup-oss/circuit-ui, pull requests merged in 2020-06, with the labels that each got.

#597 chore(configs): compile JSX and add CJS output
  package.json
  tsconfig.cjs.json
  tsconfig.json
Labels: tech

#603 feat(styles): load custom fonts
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/preview.js
  docs/advanced/fonts.story.mdx
  src/components/BaseStyles/BaseStyles.spec.tsx
  src/components/BaseStyles/BaseStyles.tsx
  src/components/BaseStyles/BaseStylesService.spec.ts
  src/components/BaseStyles/BaseStylesService.ts
  src/components/BaseStyles/__snapshots__/BaseStylesService.spec.js.snap
  src/components/BaseStyles/__snapshots__/BaseStylesService.spec.ts.snap
  src/components/BaseStyles/index.ts
Labels: feature

#604 feat(components): use smaller icons
  .storybook/components/Icons.js
  docs/advanced/icons.story.mdx
  docs/introduction/getting-started.story.mdx
  package.json
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.spec.tsx.snap
  src/components/Calendar/__snapshots__/RangePicker.spec.js.snap
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/Carousel/components/Buttons/__snapshots__/Buttons.spec.js.snap
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
  src/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/CurrencyInput/__snapshots__/CurrencyInput.spec.js.snap
  src/components/IconButton/IconButton.tsx
  src/components/Input/Input.js
  src/components/Input/__snapshots__/Input.spec.js.snap
  src/components/SearchInput/__snapshots__/SearchInput.spec.js.snap
  src/components/Select/Select.js
  src/components/Select/__snapshots__/Select.spec.js.snap
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/SortArrow/SortArrow.js
  src/components/Table/components/SortArrow/__snapshots__/SortArrow.spec.js.snap
  src/components/Table/components/TableHead/__snapshots__/TableHead.spec.js.snap
  src/components/Table/components/TableHeader/__snapshots__/TableHeader.spec.js.snap
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
  yarn.lock
Labels: feature

#596 feat(cli): add Button codemods
  .cz-config.js
  .eslintrc.js
  package.json
  src/cli/index.ts
  src/cli/migrate/__testfixtures__/button-variant-enum.input.js
  src/cli/migrate/__testfixtures__/button-variant-enum.output.js
  src/cli/migrate/__tests__/transforms.spec.js
  src/cli/migrate/button-variant-enum.ts
  src/cli/migrate/index.ts
  src/cli/migrate/utils/index.ts
  yarn.lock
Labels: tech

#601 perf: reduce dependencies
  package.json
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Badge/Badge.js
  src/components/Card/__snapshots__/Card.spec.js.snap
  src/components/CardList/CardList.story.js
  src/components/CardList/__snapshots__/CardList.spec.js.snap
  src/components/CardList/components/Item/Item.js
  src/components/CardList/components/Item/Item.spec.js
  src/components/CardList/components/Item/__snapshots__/Item.spec.js.snap
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
  src/components/ComponentsContext/withComponents.js
  src/components/IconButton/IconButton.tsx
  src/components/Input/Input.js
  src/components/Input/__snapshots__/Input.spec.js.snap
  src/components/Label/Label.js
  src/components/LoadingButton/LoadingButton.tsx
  src/components/Modal/Modal.js
  src/components/Modal/components/ModalWrapper/__snapshots__/ModalWrapper.spec.js.snap
  src/components/NotificationBanner/__snapshots__/NotificationBanner.spec.js.snap
  src/components/NotificationList/__snapshots__/NotificationList.spec.js.snap
  src/components/RadioButton/RadioButton.js
  src/components/Select/Select.js
  src/components/Select/__snapshots__/Select.spec.js.snap
  src/components/Selector/Selector.js
  src/components/Selector/__snapshots__/Selector.spec.js.snap
  src/components/SelectorGroup/__snapshots__/SelectorGroup.spec.js.snap
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/SortArrow/SortArrow.js
  src/components/Tabs/__snapshots__/Tabs.spec.js.snap
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
  src/components/Toggle/components/Switch/Switch.js
  src/components/Toggle/components/Switch/__snapshots__/Switch.spec.js.snap
  src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap
  src/styles/style-helpers.spec.ts
  src/styles/style-helpers.ts
  src/util/get-display-name.ts
  src/util/withAriaSelected.js
  src/util/withKeyboardEvents.spec.js
  yarn.lock
Labels: feature

#605 feat(components): polish Button components
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Button/Button.docs.mdx
  src/components/Button/Button.spec.tsx
  src/components/Button/Button.story.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.spec.tsx.snap
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/Carousel/components/Buttons/Buttons.js
  src/components/Carousel/components/Buttons/__snapshots__/Buttons.spec.js.snap
  src/components/CloseButton/CloseButton.js
  src/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Hamburger/Hamburger.tsx
  src/components/Hamburger/__snapshots__/Hamburger.spec.tsx.snap
  src/components/Header/Header.story.js
  src/components/IconButton/IconButton.story.tsx
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/__snapshots__/IconButton.spec.tsx.snap
  src/components/LoadingButton/LoadingButton.story.tsx
  src/components/LoadingButton/__snapshots__/LoadingButton.spec.tsx.snap
  src/components/Pagination/PageButton/PageButton.js
  src/components/Pagination/PageButton/__snapshots__/PageButton.spec.js.snap
  src/components/Pagination/PaginationButton/__snapshots__/PaginationButton.spec.js.snap
  src/components/Pagination/PaginationContainer/__snapshots__/PaginationContainer.spec.js.snap
  src/components/Pagination/__snapshots__/Pagination.spec.js.snap
  src/components/SearchInput/SearchInput.js
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  yarn.lock
Labels: design, feature

#606 feat(components): tweak components
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Anchor/Anchor.tsx
  src/components/Anchor/__snapshots__/Anchor.spec.tsx.snap
  src/components/Badge/Badge.js
  src/components/Badge/__snapshots__/Badge.spec.js.snap
  src/components/Button/Button.tsx
  src/components/Card/Card.js
  src/components/Card/__snapshots__/Card.spec.js.snap
  src/components/CardList/__snapshots__/CardList.spec.js.snap
  src/components/Col/Col.js
  src/components/Col/__snapshots__/Col.spec.js.snap
  src/components/Modal/components/ModalWrapper/__snapshots__/ModalWrapper.spec.js.snap
  src/components/Notification/components/Icon/Icon.js
  src/components/Notification/components/Icon/__snapshots__/Icon.spec.js.snap
  src/components/NotificationList/__snapshots__/NotificationList.spec.js.snap
  src/components/Toggle/Toggle.js
  src/components/Toggle/Toggle.story.js
  src/components/Toggle/__snapshots__/Toggle.spec.js.snap
Labels: bug, feature

#608 feat(cli): add component codemods
  src/cli/migrate/__testfixtures__/component-names-v2.input.js
  src/cli/migrate/__testfixtures__/component-names-v2.output.js
  src/cli/migrate/__testfixtures__/component-static-properties.input.js
  src/cli/migrate/__testfixtures__/component-static-properties.output.js
  src/cli/migrate/__tests__/transforms.spec.js
  src/cli/migrate/component-names-v2.ts
  src/cli/migrate/component-static-properties.ts
  src/cli/migrate/utils/index.ts
Labels: feature

#599 docs: add migration guide
  MIGRATION.md
  README.md
  docs/introduction/welcome.story.mdx
Labels: docs

#607 feat(components): remove static properties
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Badge/Badge.js
  src/components/Badge/Badge.spec.js
  src/components/Badge/Badge.story.js
  src/components/Blockquote/Blockquote.js
  src/components/Blockquote/Blockquote.spec.js
  src/components/Blockquote/Blockquote.story.js
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/ButtonGroup.spec.js
  src/components/ButtonGroup/ButtonGroup.story.js
  src/components/Card/Card.js
  src/components/Card/Card.spec.js
  src/components/Card/Card.story.js
  src/components/Card/components/Footer/Footer.js
  src/components/Card/components/Footer/Footer.spec.js
  src/components/CardList/components/Item/Item.js
  src/components/Checkbox/Checkbox.js
  src/components/InlineMessage/InlineMessage.js
  src/components/InlineMessage/InlineMessage.spec.js
  src/components/InlineMessage/InlineMessage.story.js
  src/components/InlineMessage/__snapshots__/InlineMessage.spec.js.snap
  src/components/Input/Input.js
  src/components/Input/Input.spec.js
  src/components/Modal/components/ModalWrapper/ModalWrapper.js
  src/components/Notification/Notification.story.js
  src/components/Notification/components/Icon/Icon.js
  src/components/Notification/components/Icon/Icon.spec.js
  src/components/NotificationList/NotificationList.js
  src/components/Popover/Popover.js
  src/components/Popover/Popover.spec.js
  src/components/Popover/Popover.story.js
  src/components/Popover/PopoverService.js
  src/components/Select/Select.js
  src/components/Step/examples/MultiStepForm.js
  src/components/Step/examples/YesOrNoSlider.js
  src/components/SubHeading/SubHeading.js
  src/components/SubHeading/SubHeading.story.js
  src/components/Table/Table.story.js
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/TableBody/TableBody.js
  src/components/Table/components/TableBody/__snapshots__/TableBody.spec.js.snap
  src/components/Table/components/TableCell/TableCell.js
  src/components/Table/components/TableCell/TableCell.story.js
  src/components/Table/components/TableHead/__snapshots__/TableHead.spec.js.snap
  src/components/Table/components/TableHeader/TableHeader.js
  src/components/Table/components/TableHeader/TableHeader.spec.js
  src/components/Table/components/TableHeader/TableHeader.story.js
  src/components/Table/components/TableHeader/__snapshots__/TableHeader.spec.js.snap
  src/components/Tabs/components/TabList/TabList.js
  src/components/TextArea/TextArea.js
  src/components/Tooltip/Tooltip.js
  src/components/Tooltip/Tooltip.spec.js
  src/components/Tooltip/Tooltip.story.js
  src/index.js
  src/styles/constants.js
  src/styles/index.js
  src/util/constants.js
  src/util/shared-prop-types.js
Labels: feature

#612 feat(components): migrate SubHeading to TypeScript
  .storybook/util/theme.js
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Heading/Heading.spec.tsx
  src/components/Heading/__snapshots__/Heading.spec.tsx.snap
  src/components/SubHeading/SubHeading.docs.mdx
  src/components/SubHeading/SubHeading.spec.tsx
  src/components/SubHeading/SubHeading.story.tsx
  src/components/SubHeading/SubHeading.tsx
  src/components/SubHeading/__snapshots__/SubHeading.spec.tsx.snap
  src/components/SubHeading/index.ts
Labels: feature

#616 fix(components): replace TabList component selector
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Tabs/__snapshots__/Tabs.spec.js.snap
  src/components/Tabs/components/Tab/Tab.js
  src/components/Tabs/components/Tab/index.js
  src/components/Tabs/components/TabList/TabList.js
Labels: bug

#617 feat(components): migrate Blockquote to TypeScript
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Blockquote/Blockquote.docs.mdx
  src/components/Blockquote/Blockquote.spec.tsx
  src/components/Blockquote/Blockquote.story.js
  src/components/Blockquote/Blockquote.story.tsx
  src/components/Blockquote/Blockquote.tsx
  src/components/Blockquote/__snapshots__/Blockquote.spec.tsx.snap
  src/components/Blockquote/index.ts
  src/components/Text/Text.tsx
Labels: feature

#620 feat(components): migrate Hr to TypeScript
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Hr/Hr.docs.mdx
  src/components/Hr/Hr.spec.tsx
  src/components/Hr/Hr.story.tsx
  src/components/Hr/Hr.tsx
  src/components/Hr/__snapshots__/Hr.spec.tsx.snap
  src/components/Hr/index.ts
Labels: feature

#624 feat(components): Migrate Badge component to typescript
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Badge/Badge.spec.tsx
  src/components/Badge/Badge.story.tsx
  src/components/Badge/Badge.tsx
  src/components/Badge/__snapshots__/Badge.spec.tsx.snap
  src/components/Badge/index.ts
Labels: feature

#619 feat(components): migrate image component to typescript
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/Carousel/components/SlideImage/__snapshots__/SlideImage.spec.js.snap
  src/components/Image/Image.docs.mdx
  src/components/Image/Image.spec.tsx
  src/components/Image/Image.story.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.spec.tsx.snap
  src/components/Image/index.ts
Labels: feature

#618 feat(components): rewrite Pagination from scratch
  .storybook/components/Statuses.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/CurrencyInput/CurrencyInput.spec.tsx
  src/components/CurrencyInput/CurrencyInput.story.tsx
  src/components/CurrencyInput/__snapshots__/CurrencyInput.spec.tsx.snap
  src/components/Pagination/PageButton/PageButton.js
  src/components/Pagination/PageButton/__snapshots__/PageButton.spec.js.snap
  src/components/Pagination/PageButton/index.js
  src/components/Pagination/Pagination.docs.mdx
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.spec.js
  src/components/Pagination/Pagination.spec.tsx
  src/components/Pagination/Pagination.story.js
  src/components/Pagination/Pagination.story.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/PaginationButton/PaginationButton.spec.js
  src/components/Pagination/PaginationButton/__snapshots__/PaginationButton.spec.js.snap
  src/components/Pagination/PaginationContainer/PaginationContainer.js
  src/components/Pagination/PaginationContainer/PaginationContainer.spec.js
  src/components/Pagination/PaginationContainer/__snapshots__/PaginationContainer.spec.js.snap
  src/components/Pagination/PaginationContainer/index.js
  src/components/Pagination/PaginationService.js
  src/components/Pagination/PaginationService.spec.js
  src/components/Pagination/PaginationService.spec.ts
  src/components/Pagination/PaginationService.ts
  src/components/Pagination/Separator/Ellipsis.js
  src/components/Pagination/__snapshots__/Pagination.spec.js.snap
  src/components/Pagination/__snapshots__/Pagination.spec.tsx.snap
  src/components/Pagination/components/PageList/PageList.spec.tsx
  src/components/Pagination/components/PageList/PageList.tsx
  src/components/Pagination/components/PageList/__snapshots__/PageList.spec.tsx.snap
  src/components/Pagination/components/PageList/index.ts
  src/components/Pagination/components/PageSelect/PageSelect.spec.tsx
  src/components/Pagination/components/PageSelect/PageSelect.tsx
  src/components/Pagination/components/PageSelect/__snapshots__/PageSelect.spec.tsx.snap
  src/components/Pagination/components/PageSelect/index.ts
  src/components/Pagination/index.ts
  src/components/Select/Select.spec.tsx
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.spec.tsx.snap
Labels: accessibility, design, feature

#622 feat(components): migrate Selector to TypeScript
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Selector/Selector.docs.mdx
  src/components/Selector/Selector.spec.tsx
  src/components/Selector/Selector.story.tsx
  src/components/Selector/Selector.tsx
  src/components/Selector/__snapshots__/Selector.spec.tsx.snap
  src/components/Selector/index.ts
  src/components/SelectorGroup/SelectorGroup.spec.tsx
  src/components/SelectorGroup/SelectorGroup.story.tsx
  src/components/SelectorGroup/SelectorGroup.tsx
  src/components/SelectorGroup/__snapshots__/SelectorGroup.spec.tsx.snap
  src/components/SelectorGroup/index.ts
Labels: feature

#623 feat(components): add subtle animations
  package.json
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Anchor/Anchor.tsx
  src/components/Anchor/__snapshots__/Anchor.spec.tsx.snap
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.spec.tsx.snap
  src/components/Calendar/__snapshots__/RangePicker.spec.js.snap
  src/components/Calendar/__snapshots__/SingleDayPicker.spec.js.snap
  src/components/Calendar/components/CalendarWrapper/__snapshots__/CalendarWrapper.spec.js.snap
  src/components/CalendarTag/__snapshots__/CalendarTag.spec.js.snap
  src/components/CalendarTagTwoStep/__snapshots__/CalendarTagTwoStep.spec.js.snap
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/Carousel/components/Buttons/__snapshots__/Buttons.spec.js.snap
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
  src/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/CurrencyInput/__snapshots__/CurrencyInput.spec.tsx.snap
  src/components/Hamburger/__snapshots__/Hamburger.spec.tsx.snap
  src/components/IconButton/__snapshots__/IconButton.spec.tsx.snap
  src/components/InlineMessage/__snapshots__/InlineMessage.spec.js.snap
  src/components/Input/__snapshots__/Input.spec.tsx.snap
  src/components/LoadingButton/__snapshots__/LoadingButton.spec.tsx.snap
  src/components/Pagination/__snapshots__/Pagination.spec.tsx.snap
  src/components/Pagination/components/PageList/__snapshots__/PageList.spec.tsx.snap
  src/components/Pagination/components/PageSelect/__snapshots__/PageSelect.spec.tsx.snap
  src/components/SearchInput/__snapshots__/SearchInput.spec.tsx.snap
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.spec.tsx.snap
  src/components/Selector/__snapshots__/Selector.spec.tsx.snap
  src/components/SelectorGroup/__snapshots__/SelectorGroup.spec.tsx.snap
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/Aggregator/__snapshots__/Aggregator.spec.js.snap
  src/components/Sidebar/components/Backdrop/__snapshots__/Backdrop.spec.js.snap
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Sidebar/components/NavItem/__snapshots__/NavItem.spec.js.snap
  src/components/Sidebar/components/SubNavList/__snapshots__/SubNavList.spec.js.snap
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/SortArrow/__snapshots__/SortArrow.spec.js.snap
  src/components/Table/components/TableBody/__snapshots__/TableBody.spec.js.snap
  src/components/Table/components/TableCell/__snapshots__/TableCell.spec.js.snap
  src/components/Table/components/TableHead/__snapshots__/TableHead.spec.js.snap
  src/components/Table/components/TableHeader/__snapshots__/TableHeader.spec.js.snap
  src/components/Tag/Tag.js
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/components/TextArea/__snapshots__/TextArea.spec.tsx.snap
  src/components/Tooltip/__snapshots__/Tooltip.spec.js.snap
  src/components/ValidationHint/__snapshots__/ValidationHint.spec.tsx.snap
  yarn.lock
Labels: design, feature
