Repository sumup-oss/circuit-ui, pull requests merged in 2020-04, with the labels that each got.

#541 feat(components): rename notification components
  src/__snapshots__/storyshots.spec.js.snap
  src/components/InlineMessage/InlineMessage.docs.mdx
  src/components/InlineMessage/InlineMessage.js
  src/components/InlineMessage/InlineMessage.spec.js
  src/components/InlineMessage/InlineMessage.story.js
  src/components/InlineMessage/__snapshots__/InlineMessage.spec.js.snap
  src/components/InlineMessage/index.js
  src/components/InlineNotification/InlineNotification.docs.mdx
  src/components/Message/Message.docs.mdx
  src/components/Notification/Notification.docs.mdx
  src/components/Notification/Notification.js
  src/components/Notification/Notification.spec.js
  src/components/Notification/Notification.story.js
  src/components/Notification/__snapshots__/Notification.spec.js.snap
  src/components/Notification/components/Button/Button.js
  src/components/Notification/components/Button/Button.spec.js
  src/components/Notification/components/Button/__snapshots__/Button.spec.js.snap
  src/components/Notification/components/Icon/Icon.js
  src/components/Notification/components/Icon/Icon.spec.js
  src/components/Notification/components/Icon/__snapshots__/Icon.spec.js.snap
  src/components/Notification/components/NotificationWarning.js
  src/components/Notification/components/index.js
  src/components/Notification/index.js
  src/components/Notification/notification-error.svg
  src/components/Notification/notification-success.svg
  src/components/NotificationBanner/NotificationBanner.js
  src/components/NotificationBanner/NotificationBanner.story.js
  src/components/NotificationList/NotificationList.js
  src/components/NotificationList/NotificationList.story.js
  src/index.js
Labels: feature

#562 feat(components): pass initial value to AutocompleteInput
  src/__snapshots__/storyshots.spec.js.snap
  src/components/AutoCompleteInput/AutoCompleteInput.docs.mdx
  src/components/AutoCompleteInput/AutoCompleteInput.js
  src/components/AutoCompleteInput/AutoCompleteInput.spec.js
  src/components/AutoCompleteInput/AutoCompleteInput.story.js
Labels: feature

#565 fix(components): update clearfix to improve accessibility
  src/__snapshots__/storyshots.spec.js.snap
  src/components/CreditCardDetails/__snapshots__/CreditCardDetails.spec.js.snap
  src/components/InlineElements/__snapshots__/InlineElements.spec.js.snap
  src/components/Row/__snapshots__/Row.spec.js.snap
  src/styles/style-helpers.js
Labels: accessibility, bug

#567 feat(components): update InfoIcon
  src/__snapshots__/storyshots.spec.js.snap
  src/components/InfoIcon/InfoIcon.js
  src/components/InfoIcon/__snapshots__/InfoIcon.spec.js.snap
  src/components/InfoIcon/info.svg
Labels: design

#563 feat(configs): configure TypeScript build system
  .babelrc
  .eslintignore
  .eslintrc.js
  .github/workflows/deploy.yml
  .storybook/main.js
  jest.config.js
  jsconfig.json
  lint-staged.config.js
  package.json
  plopfile.js
  src/components/Sidebar/components/Aggregator/Aggregator.spec.js
  src/index.js
  src/styles/style-helpers.js
  src/themes/circuit.js
  src/types/theme.ts
  src/util/regex.js
  tsconfig.eslint.json
  tsconfig.json
  yarn.lock
Labels: tech

#576 feat(utils): migrate style helpers to TypeScript
  .storybook/components/Icons.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/BaseStyles/__snapshots__/BaseStylesService.spec.js.snap
  src/components/Button/components/RegularButton/RegularButton.js
  src/components/InlineElements/InlineElements.js
  src/components/NotificationList/NotificationList.js
  src/components/NotificationList/__snapshots__/NotificationList.spec.js.snap
  src/components/Pagination/PageButton/PageButton.js
  src/components/Pagination/PageButton/__snapshots__/PageButton.spec.js.snap
  src/components/Pagination/PaginationButton/__snapshots__/PaginationButton.spec.js.snap
  src/components/Pagination/__snapshots__/Pagination.spec.js.snap
  src/components/ProgressBar/ProgressBar.js
  src/components/ProgressBar/__snapshots__/ProgressBar.spec.js.snap
  src/components/Row/Row.js
  src/styles/style-helpers.js
  src/styles/style-helpers.spec.js
  src/styles/style-helpers.ts
Labels: feature
