Repository sumup-oss/circuit-ui, pull requests merged in 2020-11, with the labels that each got.

#709 docs: fix @sumup/design-tokens URL in Theme docs
  docs/advanced/theme.stories.mdx
Labels: documentation

#716 fix(components): tweak usage of new brand colors
  package.json
  src/components/Anchor/Anchor.tsx
  src/components/Anchor/__snapshots__/Anchor.spec.tsx.snap
  src/components/Badge/__snapshots__/Badge.spec.tsx.snap
  src/components/BaseStyles/__snapshots__/BaseStylesService.spec.ts.snap
  src/components/CalendarTag/__snapshots__/CalendarTag.spec.js.snap
  src/components/CalendarTagTwoStep/__snapshots__/CalendarTagTwoStep.spec.js.snap
  src/components/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
  src/components/Input/Input.tsx
  src/components/Input/__snapshots__/Input.spec.tsx.snap
  src/components/RadioButton/__snapshots__/RadioButton.spec.tsx.snap
  src/components/RadioButtonGroup/__snapshots__/RadioButtonGroup.spec.tsx.snap
  src/components/Sidebar/components/Aggregator/__snapshots__/Aggregator.spec.tsx.snap
  src/components/Sidebar/components/SubNavList/SubNavList.js
  src/components/Sidebar/components/SubNavList/__snapshots__/SubNavList.spec.js.snap
  src/components/Tag/__snapshots__/Tag.spec.tsx.snap
  src/components/TextArea/__snapshots__/TextArea.spec.tsx.snap
  src/util/shared-prop-types.js
  yarn.lock
Labels: accessibility, design

#717 feat(deps): upgrade all dependencies
  .eslintignore
  .eslintrc.js
  .github/dependabot.yml
  jest.config.js
  package.json
  scripts/.eslintrc.js
  src/cli/migrate/__tests__/migrate.spec.js
  src/cli/migrate/currency-utils.ts
  src/cli/migrate/utils/index.ts
  src/components/Anchor/Anchor.spec.tsx
  src/components/Anchor/Anchor.tsx
  src/components/BaseStyles/BaseStyles.tsx
  src/components/Button/Button.spec.tsx
  src/components/Button/Button.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/CurrencyInput/CurrencyInput.spec.tsx
  src/components/Hamburger/Hamburger.spec.tsx
  src/components/Hr/Hr.tsx
  src/components/InlineMessage/InlineMessage.stories.tsx
  src/components/LoadingButton/LoadingButton.spec.tsx
  src/components/Modal/Modal.spec.tsx
  src/components/Notification/Notification.tsx
  src/components/NotificationBanner/NotificationBanner.tsx
  src/components/NotificationList/NotificationList.tsx
  src/components/Pagination/Pagination.spec.tsx
  src/components/Pagination/components/PageList/PageList.spec.tsx
  src/components/Pagination/components/PageSelect/PageSelect.spec.tsx
  src/components/ProgressBar/ProgressBar.spec.tsx
  src/components/ProgressBar/ProgressBar.stories.tsx
  src/components/ProgressBar/ProgressBar.tsx
  src/components/ProgressBar/__snapshots__/ProgressBar.spec.tsx.snap
  src/components/Select/Select.tsx
  src/components/Sidebar/components/Aggregator/Aggregator.spec.tsx
  src/components/Sidebar/components/Aggregator/Aggregator.tsx
  src/components/Spinner/Spinner.stories.tsx
  src/components/Step/hooks/use-step.spec.js
  src/components/Text/Text.spec.tsx
  src/components/Toggle/Toggle.tsx
  src/components/ValidationHint/ValidationHint.spec.tsx
  src/hooks/use-click-handler.spec.ts
  src/hooks/use-component-size.spec.js
  src/styles/styled.ts
  src/util/get-display-name.ts
  src/util/test-utils.tsx
  src/util/type-check.ts
  tsconfig.eslint.json
  yarn.lock
Labels: tech
