Repository sumup-oss/circuit-ui, pull requests merged in 2020-05, with the labels that each got.

#580 feat(configs): improve Jest config for TypeScript
  .npmignore
  README.md
  docs/introduction/contributing.story.mdx
  jest.config.js
  jest.setup.js
  package.json
  scripts/static-styles/config.js
  src/types/global.d.ts
  src/util/test-utils.tsx
  tsconfig.json
  yarn.lock
Labels: tech

#583 feat(components): add Anchor component
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Anchor/Anchor.docs.mdx
  src/components/Anchor/Anchor.spec.tsx
  src/components/Anchor/Anchor.story.tsx
  src/components/Anchor/Anchor.tsx
  src/components/Anchor/__snapshots__/Anchor.spec.tsx.snap
  src/components/Anchor/index.ts
  src/components/Blockquote/Blockquote.story.js
  src/components/List/List.story.js
  src/index.js
  src/styles/style-helpers.spec.js
  src/styles/style-helpers.ts
Labels: design, feature

#582 feat(components): migrate Button to TypeScript
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Button/Button.docs.mdx
  src/components/Button/Button.js
  src/components/Button/Button.spec.js
  src/components/Button/Button.spec.tsx
  src/components/Button/Button.story.js
  src/components/Button/Button.story.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.spec.js.snap
  src/components/Button/__snapshots__/Button.spec.tsx.snap
  src/components/Button/components/PlainButton/PlainButton.js
  src/components/Button/components/PlainButton/PlainButton.spec.js
  src/components/Button/components/PlainButton/__snapshots__/PlainButton.spec.js.snap
  src/components/Button/components/PlainButton/index.js
  src/components/Button/components/RegularButton/RegularButton.js
  src/components/Button/components/RegularButton/RegularButton.spec.js
  src/components/Button/components/RegularButton/__snapshots__/RegularButton.spec.js.snap
  src/components/Button/constants.ts
  src/components/Button/index.js
  src/components/Button/index.ts
  src/components/ButtonGroup/ButtonGroup.story.js
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/Carousel/components/Buttons/__snapshots__/Buttons.spec.js.snap
  src/components/LoadingButton/LoadingButton.story.js
  src/components/LoadingButton/__snapshots__/LoadingButton.spec.js.snap
  src/components/LoadingButton/components/Button/__snapshots__/Button.spec.js.snap
  src/components/Modal/Modal.embed.story.js
  src/components/Modal/Modal.story.js
  src/components/Notification/Notification.story.js
  src/components/Pagination/PageButton/PageButton.js
  src/components/Pagination/PageButton/__snapshots__/PageButton.spec.js.snap
  src/components/Pagination/PaginationButton/PaginationButton.js
  src/components/Pagination/PaginationButton/PaginationButton.spec.js
  src/components/Pagination/PaginationButton/__snapshots__/PaginationButton.spec.js.snap
  src/components/Pagination/PaginationContainer/PaginationContainer.js
  src/components/Pagination/__snapshots__/Pagination.spec.js.snap
  src/components/Popover/Popover.story.js
  src/components/Spacing/Spacing.story.js
  src/components/Step/examples/CarouselSlider.js
  src/components/Step/examples/MultiStepForm.js
  src/components/Step/examples/YesOrNoSlider.js
  yarn.lock
Labels: feature

#588 feat(components): migrate Hamburger to TypeScript
  scripts/static-styles/config.js
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Button/__snapshots__/Button.spec.tsx.snap
  src/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Hamburger/Hamburger.js
  src/components/Hamburger/Hamburger.spec.tsx
  src/components/Hamburger/Hamburger.story.tsx
  src/components/Hamburger/Hamburger.tsx
  src/components/Hamburger/__snapshots__/Hamburger.spec.js.snap
  src/components/Hamburger/__snapshots__/Hamburger.spec.tsx.snap
  src/components/Hamburger/index.ts
  src/components/IconButton/__snapshots__/IconButton.spec.tsx.snap
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Tag/__snapshots__/Tag.spec.js.snap
Labels: feature

#586 feat(components): add focus styles to all relevant components
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Badge/Badge.docs.mdx
  src/components/Badge/Badge.js
  src/components/Badge/Badge.spec.js
  src/components/Badge/Badge.story.js
  src/components/Badge/__snapshots__/Badge.spec.js.snap
  src/components/CalendarTag/__snapshots__/CalendarTag.spec.js.snap
  src/components/CalendarTagTwoStep/__snapshots__/CalendarTagTwoStep.spec.js.snap
  src/components/CardList/components/Item/Item.js
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/__snapshots__/RadioButton.spec.js.snap
  src/components/RadioButtonGroup/__snapshots__/RadioButtonGroup.spec.js.snap
  src/components/Select/Select.js
  src/components/Select/__snapshots__/Select.spec.js.snap
  src/components/Selector/Selector.js
  src/components/Selector/__snapshots__/Selector.spec.js.snap
  src/components/SelectorGroup/__snapshots__/SelectorGroup.spec.js.snap
  src/components/Table/__snapshots__/Table.spec.js.snap
  src/components/Table/components/SortArrow/SortArrow.js
  src/components/Table/components/SortArrow/SortArrow.spec.js
  src/components/Table/components/SortArrow/__snapshots__/SortArrow.spec.js.snap
  src/components/Table/components/TableBody/TableBody.js
  src/components/Table/components/TableHead/__snapshots__/TableHead.spec.js.snap
  src/components/Table/components/TableHeader/TableHeader.js
  src/components/Table/components/TableHeader/TableHeader.spec.js
  src/components/Table/components/TableHeader/__snapshots__/TableHeader.spec.js.snap
  src/components/Table/components/TableRow/TableRow.js
  src/components/Table/components/TableRow/TableRow.spec.js
  src/components/Table/components/TableRow/__snapshots__/TableRow.spec.js.snap
  src/components/Tabs/__snapshots__/Tabs.spec.js.snap
  src/components/Tabs/components/Tab/Tab.js
  src/components/Tabs/components/Tab/__snapshots__/Tab.spec.js.snap
  src/components/Tag/Tag.js
  src/components/Tag/Tag.story.js
  src/components/Tag/__snapshots__/Tag.spec.js.snap
  src/components/Toggle/Toggle.js
  src/components/Toggle/__snapshots__/Toggle.spec.js.snap
  src/components/Toggle/components/Switch/Switch.js
  src/components/Toggle/components/Switch/__snapshots__/Switch.spec.js.snap
  src/styles/style-helpers.spec.ts
  src/styles/style-helpers.ts
  src/util/key-codes.js
Labels: accessibility, design

#587 feat(components): Combine label with form input components
  src/__snapshots__/storyshots.spec.js.snap
  src/components/AutoCompleteInput/AutoCompleteInput.story.js
  src/components/AutoCompleteInput/__snapshots__/AutoCompleteInput.spec.js.snap
  src/components/AutoCompleteTags/__snapshots__/AutoCompleteTags.spec.js.snap
  src/components/CurrencyInput/CurrencyInput.story.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/__snapshots__/SimpleCurrencyInput.spec.js.snap
  src/components/Input/Input.js
  src/components/Input/Input.spec.js
  src/components/Input/Input.story.js
  src/components/Input/__snapshots__/Input.spec.js.snap
  src/components/SearchInput/SearchInput.story.js
  src/components/SearchInput/__snapshots__/SearchInput.spec.js.snap
  src/components/Select/Select.js
  src/components/Select/Select.spec.js
  src/components/Select/Select.story.js
  src/components/Select/__snapshots__/Select.spec.js.snap
  src/components/TextArea/TextArea.spec.js
  src/components/TextArea/TextArea.story.js
  src/components/TextArea/__snapshots__/TextArea.spec.js.snap
Labels: accessibility, feature

#590 feat(utils): extract number utils to a separate package
  package.json
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Col/utils.js
  src/components/CurrencyInput/CurrencyInput.docs.mdx
  src/components/CurrencyInput/CurrencyInput.js
  src/components/CurrencyInput/CurrencyInput.spec.js
  src/components/CurrencyInput/CurrencyInput.story.js
  src/components/CurrencyInput/CurrencyInputService.js
  src/components/CurrencyInput/CurrencyInputService.spec.js
  src/components/CurrencyInput/__snapshots__/CurrencyInput.spec.js.snap
  src/components/CurrencyInput/components/SimpleCurrencyInput/SimpleCurrencyInput.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/SimpleCurrencyInput.spec.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/SimpleCurrencyInput.story.js
  src/components/CurrencyInput/components/SimpleCurrencyInput/__snapshots__/SimpleCurrencyInput.spec.js.snap
  src/components/CurrencyInput/components/SimpleCurrencyInput/index.js
  src/components/CurrencyInput/components/index.js
  src/components/CurrencyInput/index.js
  src/components/Modal/Modal.js
  src/components/Portal/Portal.js
  src/components/Tabs/Tabs.js
  src/index.js
  src/util/__snapshots__/currency.spec.js.snap
  src/util/currency.js
  src/util/currency.spec.js
  src/util/fp.js
  src/util/get-validation-errors.js
  src/util/helpers.js
  src/util/index.js
  src/util/numbers.js
  src/util/numbers.spec.js
  src/util/ownerDocument.js
  src/util/shared-prop-types.js
  yarn.lock
Labels: feature
