Repository sumup-oss/circuit-ui, pull requests merged in 2020-08, with the labels that each got.

#655 test(configs): set up visual testing with Chromatic
  .github/workflows/chromatic.yml
  .gitignore
  .storybook/public/images/chromatic.svg
  README.md
  docs/introduction/contributing.story.mdx
  package.json
  src/__snapshots__/storyshots.spec.js.snap
  src/components/Calendar/RangePicker.js
  src/components/Carousel/__fixtures__/index.js
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/Carousel/components/Slide/Slide.story.js
  src/components/Carousel/components/SlideImage/SlideImage.spec.js
  src/components/Carousel/components/SlideImage/__snapshots__/SlideImage.spec.js.snap
  src/components/Image/Image.story.tsx
  src/components/Modal/Modal.embed.story.tsx
  src/components/Modal/Modal.story.tsx
  src/components/Step/Step.story.js
  src/components/Step/examples/CarouselSlider.js
  src/components/Step/examples/YesOrNoSlider.js
  yarn.lock
Labels: tech

#656 test(configs): remove storyshots
  .storybook/.babelrc
  .storybook/preview.js
  babel.config.json
  package.json
  src/__snapshots__/storyshots.spec.js.snap
  src/storyshots.spec.js
  yarn.lock
Labels: tech

#663 fix(components): don't mix default and named exports
  src/components/ComponentsContext/index.js
  src/index.js
  src/util/test-utils.tsx
Labels: bug

#667 feat(components): move Aggregator to TypeScript and add tracking to it (via useClickTracker)
  src/components/Sidebar/components/Aggregator/Aggregator.js
  src/components/Sidebar/components/Aggregator/Aggregator.spec.tsx
  src/components/Sidebar/components/Aggregator/Aggregator.tsx
  src/components/Sidebar/components/Aggregator/__snapshots__/Aggregator.spec.tsx.snap
  src/components/Sidebar/components/Aggregator/index.tsx
Labels: feature

#665 feat(components): add label and validation hint to RadioButtonGroup
  src/components/RadioButtonGroup/RadioButtonGroup.stories.tsx
  src/components/RadioButtonGroup/RadioButtonGroup.tsx
  src/components/RadioButtonGroup/__snapshots__/RadioButtonGroup.spec.tsx.snap
Labels: feature
