Repository sumup-oss/circuit-ui, pull requests merged in 2021-03, with the labels that each got.

#833 fix: component SingleDayPicker wrong usage example
  src/components/Calendar/SingleDayPicker.stories.js
Labels: bug, documentation

#834 feat(components): add promo variant to Badge
  src/components/Badge/Badge.spec.tsx
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
  src/components/Badge/__snapshots__/Badge.spec.tsx.snap
  src/components/Step/Step.stories.js
Labels: design, feature

#821 feat(components): change Button shape to a pill
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.spec.tsx.snap
  src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.tsx.snap
  src/components/Calendar/__snapshots__/RangePicker.spec.js.snap
  src/components/Calendar/__snapshots__/SingleDayPicker.spec.js.snap
  src/components/Calendar/components/CalendarWrapper/CalendarWrapper.js
  src/components/Calendar/components/CalendarWrapper/__snapshots__/CalendarWrapper.spec.js.snap
  src/components/Card/components/Header/Header.tsx
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/Carousel/components/Buttons/__snapshots__/Buttons.spec.js.snap
  src/components/CloseButton/__snapshots__/CloseButton.spec.tsx.snap
  src/components/Hamburger/__snapshots__/Hamburger.spec.tsx.snap
  src/components/Header/Header.stories.tsx
  src/components/IconButton/__snapshots__/IconButton.spec.tsx.snap
  src/components/LoadingButton/__snapshots__/LoadingButton.spec.tsx.snap
  src/components/Modal/Modal.spec.tsx
  src/components/Pagination/Pagination.docs.mdx
  src/components/Pagination/__snapshots__/Pagination.spec.tsx.snap
  src/components/Pagination/components/PageList/PageList.tsx
  src/components/Pagination/components/PageList/__snapshots__/PageList.spec.tsx.snap
  src/components/SearchInput/SearchInput.tsx
  src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
  src/components/Sidebar/components/CloseButton/CloseButton.js
  src/components/Sidebar/components/CloseButton/__snapshots__/CloseButton.spec.js.snap
  src/components/Tag/__snapshots__/Tag.spec.tsx.snap
  src/util/test-utils.tsx
Labels: design

#825 refactor(components): migrate InlineElements to TypeScript
  src/components/Header/Header.tsx
  src/components/InlineElements/InlineElements.spec.tsx
  src/components/InlineElements/InlineElements.stories.tsx
  src/components/InlineElements/InlineElements.tsx
  src/components/InlineElements/__snapshots__/InlineElements.spec.tsx.snap
  src/components/InlineElements/index.ts
  src/index.ts
Labels: feature

#822 fix(components): add margins to all ButtonGroup child elements
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.tsx.snap
Labels: bug

#832 feat(components): add spacing mixin
  src/styles/style-helpers.spec.tsx
  src/styles/style-helpers.ts
Labels: feature

#831 feat(components): deprecate default component spacing
  README.md
  src/components/Anchor/Anchor.tsx
  src/components/Checkbox/Checkbox.spec.tsx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
  src/components/Heading/Heading.stories.tsx
  src/components/Heading/Heading.tsx
  src/components/InlineMessage/InlineMessage.stories.tsx
  src/components/InlineMessage/InlineMessage.tsx
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
  src/components/Input/__snapshots__/Input.spec.tsx.snap
  src/components/List/List.stories.tsx
  src/components/List/List.tsx
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.tsx
  src/components/Selector/Selector.spec.tsx
  src/components/Selector/Selector.stories.tsx
  src/components/Selector/Selector.tsx
  src/components/Selector/__snapshots__/Selector.spec.tsx.snap
  src/components/SelectorGroup/SelectorGroup.stories.tsx
  src/components/SubHeading/SubHeading.stories.tsx
  src/components/SubHeading/SubHeading.tsx
  src/components/Text/Text.stories.tsx
  src/components/Text/Text.tsx
  src/components/TextArea/__snapshots__/TextArea.spec.tsx.snap
  src/components/Toggle/Toggle.stories.tsx
  src/components/Toggle/Toggle.tsx
  src/util/deprecate.ts
Labels: feature

#842 fix(components): prevent validation icons from shrinking
  src/components/ValidationHint/ValidationHint.tsx
  src/components/ValidationHint/__snapshots__/ValidationHint.spec.tsx.snap
Labels: bug

#849 feat(components): tweak spacing mixin
  src/styles/style-helpers.spec.tsx
  src/styles/style-helpers.ts
Labels: feature

#851 fix(components): improve grid component types
  src/components/Col/Col.js
  src/components/Col/utils.js
  src/components/Col/utils.spec.js
  src/components/Table/utils.js
Labels: bug

#850 docs(components): document the style mixins
  .storybook/preview.js
  docs/advanced/tracking.stories.mdx
  src/components/Anchor/Anchor.tsx
  src/components/Badge/Badge.tsx
  src/components/BaseStyles/BaseStylesService.ts
  src/components/Button/Button.tsx
  src/components/Calendar/components/CalendarWrapper/CalendarWrapper.js
  src/components/CalendarTagTwoStep/CalendarTagTwoStep.js
  src/components/Card/Card.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/IconButton/IconButton.tsx
  src/components/InlineElements/InlineElements.tsx
  src/components/Input/Input.tsx
  src/components/Label/Label.tsx
  src/components/List/List.tsx
  src/components/LoadingButton/LoadingButton.tsx
  src/components/NotificationBanner/NotificationBanner.tsx
  src/components/ProgressBar/ProgressBar.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioButtonGroup/RadioButtonGroup.tsx
  src/components/Row/Row.js
  src/components/Select/Select.tsx
  src/components/Selector/Selector.tsx
  src/components/Table/Table.js
  src/components/Table/components/SortArrow/SortArrow.js
  src/components/Table/components/TableHeader/TableHeader.js
  src/components/Table/components/TableRow/TableRow.js
  src/components/Tabs/components/Tab/Tab.js
  src/components/Tabs/components/TabList/TabList.js
  src/components/Tag/Tag.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/components/Switch/Switch.tsx
  src/components/Tooltip/Tooltip.js
  src/components/ValidationHint/ValidationHint.tsx
  src/index.ts
  src/styles/style-helpers.ts
  src/styles/style-mixins.docs.mdx
  src/styles/style-mixins.spec.tsx
  src/styles/style-mixins.stories.tsx
  src/styles/style-mixins.ts
  src/util/deprecate.ts
Labels: documentation
